- _sub/compute/k8s-servicebroker/main.tf
Added Annotations to existing namespace using kubectl and to Pods using helm chart.
> Added annotations to ServiceBroker

- _sub/compute/k8s-harbor/harbor.tf
- _sub/compute/k8s-harbor/vars.tf
- _sub/database/rds-postgres-harbor/db-server-instance.tf
- _sub/database/rds-postgres-harbor/outputs.tf
- _sub/database/rds-postgres-harbor/prepare-databases.tf
- _sub/database/rds-postgres-harbor/securitygroup.tf
- _sub/database/rds-postgres-harbor/vars.tf
- _sub/security/random-string-generate/main.tf
- _sub/security/random-string-generate/outputs.tf
- _sub/security/random-string-generate/vars.tf
- _sub/security/ssm-parameter-store/main.tf
- _sub/security/ssm-parameter-store/vars.tf
- compute/eks-ec2/outputs.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Harbor module refactored to use feature-toggle.
Added new module for generating random strings/password
> feature-toggle harbor. Added support for storing password in param store

- _sub/compute/k8s-traefik/main.tf
- _sub/compute/k8s-traefik/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
We can now specify desired Traefik version when referencing main module.
> Enable passing Traefik version to main EKS module

- _sub/compute/ecr-repo/main.tf
- _sub/compute/ecr-repo/outputs.tf
- _sub/compute/ecr-repo/vars.tf
- _sub/compute/ecr-repo/versions.tf
- compute/ecr-repo/main.tf
- compute/ecr-repo/vars.tf
A one to one migration of ECR repo module. You still have to migrate states.
> Migrated ECR repo one to one and modularized (if that's a word) it.

- security/org-account-assume/main.tf
> Finally found the mistake with confusion of resources related to IAM

- _sub/compute/k8s-kiam/main.tf
- compute/k8s-services/main.tf
Updated the infrastructure modules to have KIAM run under Helm 3.
> Updated KIAM to Helm3.

- _sub/compute/k8s-traefik-v2/main.tf
- _sub/compute/k8s-traefik-v2/vars.tf
- _sub/compute/k8s-traefik/main.tf
- _sub/compute/k8s-traefik/vars.tf
> EKS: Traefik QoS 'Burstable'

- _sub/compute/k8s-kiam/main.tf
- _sub/compute/k8s-kiam/tolerations.yaml
- _sub/compute/k8s-kiam/vars.tf
Objective:
- Classifies KIAM QoS as "Burstable" (by setting resource requests)
- Tolerate all node taints
> Kiam qos and toleration

- _sub/compute/k8s-kiam/main.tf
- _sub/compute/k8s-kiam/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Modified kiam module to use chart version instead of the agent and server version tags.
> Modified kiam module to use chart version.

- _sub/database/postgres/main.tf
- _sub/database/postgres/vars.tf
- database/postgres/main.tf
- database/postgres/vars.tf
https://github.com/dfds/cloudplatform/issues/173
> Allow setting of RDS engine version

- test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl
Included these two services into QA environment.
> Added Metrics server and goldpinger to QA env

- _sub/compute/helm-kube-prometheus-stack/main.tf
- _sub/compute/helm-kube-prometheus-stack/outputs.tf
- _sub/compute/helm-kube-prometheus-stack/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/outputs.tf
- compute/k8s-services/vars.tf
- compute/k8s-services/versions.tf
- src/qa-test-eks.sh
- test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl
Also edited Prometheus default password for Grafana Admin to be random generated if not specified.
> Add prometheus to qa

- test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl
disable: 
monitoring namespace
prometheus stack
goldpinger
metrics-server
crossplane
> turned off qa modules to aid troubleshoot

- test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl
remove prometheus-stack due to issue identified
enable crossplane
> remove prometheus-stack due to issue identified

- _sub/compute/helm-atlantis/main.tf
- _sub/compute/helm-atlantis/values/values.yaml
- _sub/compute/helm-atlantis/vars.tf
- azure-pipelines.yaml
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- src/qa-test-eks.sh
- test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl
This PR adds Atlantis to QA. As part of doing so, the ability to define the StorageClass has also been implemented
> Add atlantis to qa

- _sub/compute/k8s-fluxcd/dependencies.tf
- _sub/compute/k8s-fluxcd/main.tf
- _sub/compute/k8s-fluxcd/migrate-state.sh
- _sub/compute/k8s-fluxcd/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Various changes including Flux version lock and modification of the way in which manifests are applied and synched.
> Flux version lock

- _sub/compute/helm-kube-prometheus-stack/values/alertmanager-slack.yaml
Silence CPUThrottlingHigh alerts forever.
> We probably do not want to see this alert ever

- _sub/compute/k8s-fluxcd/main.tf
Also moved the delay for the CRD deployment into the manifest installation resource.
> Modify dependency for flux sync

- _sub/compute/k8s-fluxcd/main.tf
Modified dependencies to ensure Flux manifests are installed prior to the sync commencing.
> Added timeout fluxcd install

- security/org-capability-root/dependencies.tf
Added two more waf services: waf-regional and wafv2 to non-eu org policy exceptions
> Added two more waf services: waf-regional and wafv2

- src/qa-test-eks.sh
Would this work better at cleaning up IAM roles? I saw some cloudwatch roles left behind, that should be hit by this query (though these did not conflict with new QA runs).
> QA: Delete roles matching pattern, instead of specific names

- azure-pipelines.yaml
- src/qa-test-eks.sh
- Remove pipefail option
- Disable CLI pager
- Detach node role policies before delete
- Print xargs command before executing
- Separate cleanup functions for cluster and shared resources
- Fix unbound variable 
Results:
https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=367705&view=results
https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=367707&view=results
> Eks qa detach policies

- src/qa-test-eks.sh
- add extra call to cleanup_roles with clustername- prefix
> add extra call to cluster cleanup in qa script

- _sub/compute/helm-atlantis/main.tf
- _sub/compute/helm-atlantis/values/values.yaml
- _sub/compute/helm-atlantis/versions.tf
- compute/k8s-services/main.tf
100m CPU and 1Gi seems to constraint for the upper limits of Atlantis.
Bump to 1 CPU and 2 Gi memory (limit).
> Atlantis bump resource limits

- _sub/security/azure-app-registration/versions.tf
- compute/k8s-services/versions.tf
Minor version bumps for the providers:
hashicorp/azuread
hashicorp/random
> Terraform provider minor version increments

- _sub/compute/eks-addons/dependencies.tf
The information regarding EKS add-on versions, have been spread across three new documentation pages. References updated in comments.
> Update references to EKS add-on docs

- _sub/compute/helm-kube-prometheus-stack/outputs.tf
- azure-pipelines.yaml
- compute/k8s-services/outputs.tf
- src/qa-test-eks.sh
Also bumped Terragrunt version to be compatible with TF 1.x.
https://github.com/dfds/cloudplatform/issues/354
> Qa image terraform 1.x

- database/postgres-restore/versions.tf
- database/postgres/versions.tf
- network/route53-sub-zone/versions.tf
- security/adsync-qa-env/versions.tf
- security/cloudtrail-master/versions.tf
- security/iam-roles-master/versions.tf
- security/iam-roles-qa/versions.tf
- security/iam-users-master/versions.tf
- security/org-account-assume/versions.tf
- security/org-account-context/versions.tf
- security/org-capability-root/versions.tf
- security/ssh-keypair/versions.tf
> Fix for TF linter being so helpful, it removed an curly end-brace

- security/org-capability-root/dependencies.tf
In order to allow account deletion.
> aws-portal:View* --> aws-portal:*

- test/integration/eu-west-1/k8s-qa20/services/terragrunt.hcl
Version lock for Traefikv2 in QA.
Traefik v2 ALB Deployment.
> QA20 Changes

- src/qa-test-eks.sh
Tested in QA: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=394883&view=results
> Get all Network interfaces and treat it as an array instead of a space separated string

- _sub/compute/k8s-fluxcd/dependencies.tf
- _sub/compute/k8s-fluxcd/main.tf
- compute/k8s-services/versions.tf
Refactor to use data.github_branch to find branch instead of data.github_repository.main.default_branch
Issue: https://github.com/dfds/cloudplatform/issues/348
Tested in QA: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=395428&view=results
Also tested in sandbox.
> Fix problem with updating branches for flux-system

- .github/workflows/tfsec.yml
- _sub/compute/ec2-instance/vars.tf
- _sub/compute/ec2-securitygroup/main.tf
- _sub/compute/ec2-sgrule-cidr/main.tf
- _sub/compute/ec2-sgrule-sg/main.tf
- _sub/compute/eks-alb-auth/main.tf
- _sub/compute/eks-alb/main.tf
- _sub/compute/eks-cluster/eks.tf
- _sub/compute/eks-cluster/securitygroup.tf
- _sub/compute/eks-nlb/main.tf
- _sub/compute/helm-atlantis/dependencies.tf
- _sub/compute/helm-kube-prometheus-stack/vars.tf
- _sub/compute/k8s-atlantis-flux-config/dependencies.tf
- _sub/compute/k8s-traefik-flux/dependencies.tf
- _sub/compute/k8s-traefik/dependencies.tf
- _sub/monitoring/alarm-notifier/main.tf
- _sub/network/security-group-eks-node/main.tf
- _sub/security/iam-policies/vars.tf
- _sub/storage/s3-bucket-lifecycle/main.tf
- _sub/storage/s3-bucket/main.tf
- azure-pipelines.yaml
- compute/k8s-services/vars.tf
- security/adsync-qa-env/vars.tf
The PR covers:
1. No change in infrastructure functionality.
2. Add tfsec scanning on push. Report to SARIF. See it in action here: https://github.com/dfds/test_tfsec_on_infra/security/code-scanning?page=1
3. Use the #tfsec:ignore:code on many blocks and lines to remove false-positives or deliberate design choices.
4. 17 of the findings have alreayd been registered as issues on our kanban board.
> Add tfsec scanning and reporting

- compute/k8s-services/main.tf
* Make Traefik v2 main ingress controller again
* Change Traefik v2 healthcheck from /dashboard to /ping for robustness
> Make Traefik v2 main ingress controller.

- _sub/security/azure-app-registration/versions.tf
- compute/eks-ec2/versions.tf
- compute/k8s-services/versions.tf
- database/postgres-restore/versions.tf
- database/postgres/versions.tf
- network/route53-sub-zone/versions.tf
- security/adsync-qa-env/versions.tf
- security/cloudtrail-master/versions.tf
- security/iam-roles-master/versions.tf
- security/iam-roles-qa/versions.tf
- security/iam-users-master/versions.tf
- security/org-account-assume/versions.tf
- security/org-account-context/versions.tf
- security/org-account/main.tf
- security/org-capability-root/versions.tf
- security/ssh-keypair/versions.tf
- storage/s3-velero-backup/versions.tf
Tested in QA with success: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=401187&view=results
> Upgrade providers AD and AWS minor versions

- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
Just a version bump on kube-prometheus-stack to have it test in QA.
> Version bump to kube-prometheus-stack in QA.

- compute/k8s-services/versions.tf
They have now fixed their shit in a patch update.
> Update gh provider

- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
Requested in issue: https://github.com/dfds/cloudplatform/issues/457
> Make Blackbox Exporter an optional feature

- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
QA: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=413569&view=results
No issues seen in sandbox either.
> Upgrade Blackbox Exporter helm chart to 5.1.3

- .github/workflows/tfsec_pr_commenter.yml
This will flag any issues with Infracture as code according to tfsec on the pull request.
> Add In tfsec pull request commenter

- _sub/compute/eks-alb-auth/main.tf
- _sub/compute/eks-alb/main.tf
- _sub/compute/eks-cluster/eks.tf
- _sub/compute/eks-cluster/securitygroup.tf
- _sub/database/postgres-restore/main.tf
- _sub/database/postgres/main.tf
- _sub/database/rds-postgres-harbor/db-server-instance.tf
- _sub/monitoring/alarm-notifier/main.tf
- _sub/network/security-group-eks-node/main.tf
- In irrelevant modules.
- False positives
- Easy to fix and without impact.
> Remove tfsec alerts that are either:

- database/postgres/README.md
- database/postgres/main.tf
- database/postgres/vars.tf
> Add the possibility to set allocated storage in postgres

- _sub/compute/eks-cluster/vars.tf
- compute/eks-ec2/vars.tf
Issue: https://github.com/dfds/cloudplatform/issues/527
> tfsec: EKS logging

- azure-pipelines.yaml
- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
Use atlantis_image_tag  = "0.0.11
> Use dfdsdk/prime-pipeline:0.6.6

- .github/workflows/auto-release.yml
- .github/workflows/renovate.yml
- renovate.json
Update renovate to auto merge changes < minor and major
Update version of Renovate
> Add GH Action to auto release on merge to default branch

- _sub/database/postgres/main.tf
- _sub/database/postgres/vars.tf
- database/postgres/README.md
- database/postgres/main.tf
- database/postgres/vars.tf
Reverts dfds/infrastructure-modules#383
> Change lifecycle logic for postgres

- _sub/database/postgres-restore/outputs.tf
- _sub/database/postgres-restore/vars.tf
- _sub/database/postgres/outputs.tf
- _sub/database/postgres/vars.tf
- database/postgres-restore/main.tf
- database/postgres-restore/vars.tf
- database/postgres/main.tf
- database/postgres/vars.tf
> Support more SSL modes for PostgreSQL

- security/org-capability-root/dependencies.tf
Resolves dfds/cloudplatform#569.
> Remove all OpenID operations from "denyiam_policy"

- _sub/monitoring/fluentd-cloudwatch/dependencies.tf
- _sub/monitoring/fluentd-cloudwatch/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Add support to override log file retention policy
> Add ability to override which account to store the fluentd logs.

- _sub/storage/velero-flux/dependencies.tf
- _sub/storage/velero-flux/main.tf
- _sub/storage/velero-flux/vars.tf
- _sub/storage/velero-flux/versions.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
Tested in QA: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=434742&view=results
Sandbox migration documentation at: https://wiki.dfds.cloud/en/teams/devex/flux-migration
> Move Flux manifest to new git repository

- _sub/security/iam-policies/main.tf
- _sub/security/iam-policies/outputs.tf
- security/org-account/main.tf
- security/org-account/vars.tf
Support for dfds/cloudplatform#609.
> Adds SAML Idp to accounts prov. by pre-prime

- storage/s3-eks-public/main.tf
- storage/s3-eks-public/versions.tf
> Set version constraint for AWS Terraform provider used by storage module

- _sub/storage/velero-flux/dependencies.tf
- storage/s3-velero-backup/dependencies.tf
- storage/s3-velero-backup/main.tf
- storage/s3-velero-backup/vars.tf
- test/integration/_global/s3-bucket-velero/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
Reverts dfds/infrastructure-modules#417
> Revert "Replace KIAM with IRSA for Velero"

- _sub/compute/helm-kube-prometheus-stack/main.tf
- _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
- _sub/compute/helm-kube-prometheus-stack/vars.tf
- _sub/compute/k8s-subnet-exporter/dependencies.tf
- _sub/compute/k8s-subnet-exporter/main.tf
- _sub/compute/k8s-subnet-exporter/vars.tf
- _sub/compute/k8s-subnet-exporter/version.tf
- compute/k8s-services/dependencies.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- Added aws-subnet-exporter with oidc iam
- Modified kube-prometheus-stack to use oidc iam
> Feat/kiam to iam/helm kube prometheus stack

- _sub/compute/helm-crossplane/main.tf
See template from crossplane helm chart https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/templates/deployment.yaml
> fix label selector on crossplane service

- _sub/security/iam-oidc-provider/main.tf
- storage/s3-velero-backup/main.tf
You cannot combine string and null types
> Pre prime OIDC provider usage

- _sub/compute/eks-addons/dependencies.tf
> update vpccni and coredns version maps for 1.21

- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
> Upgrade to latest patch version of EBS CSI driver

- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
> Update Atlantis Docker and Helm Chart version

- _sub/storage/s3-bucket-lifecycle/main.tf
- _sub/storage/s3-bucket/main.tf
- storage/s3-velero-backup/main.tf
This PR will enable encryption on all S3 buckets. 
Tested on Velero, ALB Access Logs and k8s public bucket without finding any issues.
> Add encryption block to the bucket definition

- compute/k8s-services/main.tf
Updating Golang version and packages for exporter https://github.com/dfds/aws-subnet-exporter/commit/b9681821cee9996b4d0655a883e0eb134c9cbc93
> Update image tag for aws-subnet-exporter

- _sub/compute/k8s-fluxcd/dependencies.tf
- _sub/compute/k8s-fluxcd/main.tf
> Auto-generate platform-apps.yaml making Flux 100 percent automated

- security/org-capability-root/dependencies.tf
This PR will allow the root account to enable MFA in a capability
> denyiam policy change for root account mfa

- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
> Do not version lock Blackbox Exporter in QA

- _sub/compute/eks-addons/dependencies.tf
> Add support for AWS EKS 1.22 addons

- _sub/storage/velero-flux/dependencies.tf
- _sub/storage/velero-flux/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl
> Add support for patching the Helm chart for Velero

- _sub/storage/s3-bucket-lifecycle/main.tf
- _sub/storage/s3-bucket/main.tf
- _sub/storage/s3-cloudtrail-bucket/main.tf
- compute/eks-ec2/versions.tf
- compute/k8s-services/versions.tf
- database/postgres-restore/versions.tf
- database/postgres/versions.tf
- network/route53-sub-zone/versions.tf
- security/adsync-qa-env/versions.tf
- security/cloudtrail-master/versions.tf
- security/iam-roles-master/versions.tf
- security/iam-roles-qa/versions.tf
- security/iam-users-master/versions.tf
- security/org-account-assume/versions.tf
- security/org-account-context/versions.tf
- security/org-account/main.tf
- security/org-capability-root/versions.tf
- security/ssh-keypair/versions.tf
- storage/s3-ce-cli/versions.tf
- storage/s3-eks-public/versions.tf
- storage/s3-velero-backup/main.tf
- storage/s3-velero-backup/versions.tf
Tested upgrade with success in my sandbox.
Tested fresh install in QA with success: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=464034&view=results
> Upgrade Terraform AWS provider to 4.x

- _sub/compute/helm-kyverno/dependencies.tf
- _sub/compute/helm-kyverno/main.tf
- _sub/compute/helm-kyverno/vars.tf
- _sub/compute/helm-kyverno/versions.tf
- _sub/compute/k8s-traefik-flux/outputs.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- Added Kyverno and service nodeport and admission policies
- Updated helm-kyverno module
> kyverno service admission

- _sub/compute/k8s-crossplane-provider-confluent/dependencies.tf
- _sub/compute/k8s-crossplane-provider-confluent/main.tf
- _sub/compute/k8s-crossplane-provider-confluent/vars.tf
- _sub/compute/k8s-crossplane-provider-confluent/versions.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Enable Crossplane resources access to make use of shared configurations
> Configmaps with confluent cloud configurations in hellman

- _sub/compute/helm-kube-prometheus-stack/values/kube-state-metrics.yaml
> Track KIAM annotations on namespaces and pods

- azure-pipelines.yaml
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> Update docker images

- _sub/compute/k8s-crossplane-provider-confluent/dependencies.tf
- _sub/compute/k8s-crossplane-provider-confluent/main.tf
- _sub/compute/k8s-crossplane-provider-confluent/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
solves https://github.com/dfds/cloudplatform/issues/694
> confluent cluster configmaps

- _sub/compute/helm-kyverno/main.tf
- _sub/compute/helm-kyverno/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Increased too optimistic default resource limits for memory on Kyverno helm chart. This caused alert for 5XX errors from the api-server view in the audit logs.
> Increased too optimistic default resource limits

- _sub/compute/eks-addons/dependencies.tf
https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html
> Update vpc cni across all EKS versions

- _sub/compute/k8s-blaster-namespace/main.tf
- _sub/compute/k8s-blaster-namespace/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
This PR will add a toggle to allow is to remove the KIAM integration. It will depend upon https://github.com/dfds/infrastructure-modules/pull/527 being merged first
> Add kiam deploy toggle

- _sub/compute/helm-atlantis/main.tf
- _sub/compute/helm-atlantis/values/values.yaml
- _sub/compute/helm-atlantis/vars.tf
- compute/k8s-services/main.tf
This PR puts the webhook environment variables into Atlantis
> Atlantis changes for webhooks

- _sub/compute/helm-atlantis/values/values.yaml
this should fix the failing pod creation
> remove confluent stuff from atlantis values

- _sub/compute/helm-atlantis/values/values.yaml
The `storageClassName` is now found under `volumeClaim` in the values.
> Update specification of storage class.

- .gitignore
> mac os ignore setting

- test/integration/_global/eks-public-s3-bucket/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
This PR will update the QA hcl's to be more reflective of production for daily QA run
> Update qa vars

- _sub/security/iam-identity-center/main.tf
- _sub/security/iam-identity-center/outputs.tf
- _sub/security/iam-identity-center/versions.tf
- security/iam-identity-center-master/main.tf
- security/iam-identity-center-master/vars.tf
- security/iam-identity-center-master/versions.tf
This PR adds the required terraform modules for our AWS SSO implementation
> Add AWS SSO terraform modules

- _sub/compute/helm-kube-prometheus-stack/values/kube-state-metrics.yaml
- _sub/compute/k8s-namespace/main.tf
- compute/k8s-services/main.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
This PR will remove any "soft" uses of KIAM that are not dependent on the toggleable KIAM module
> Remove kiam kube state metrics args

- src/qa-test-eks.sh
Which prevents it from connecting to the Kubernetes cluster.
> Remove double quotes from Kubeconfig path.

- azure-pipelines.yaml
- Configured pipelines to apply the master branch and then feature branch
- Configured an exclusive lock on the QA environment so only one pipeline will be able to run at any given time
- Trigger for non-draft PR and not auto cancel on updates to the PR branch
- Trigger on push/merge to the master branch
> QA pull request flow

- .github/workflows/auto-release.yml
It was not matching files deeper in the file hierarchy.
> Fix auto release ignore

- compute/k8s-services/versions.tf
Signed-off-by: Audun Nes <audun.nes@gmail.com>
> Updated hashicorp/azuread provider

- compute/eks-ec2/versions.tf
- compute/k8s-services/versions.tf
- database/postgres-restore/versions.tf
- database/postgres/versions.tf
- network/route53-sub-zone/versions.tf
- security/adsync-qa-env/versions.tf
- security/cloudtrail-master/versions.tf
- security/iam-identity-center-master/versions.tf
- security/iam-roles-master/versions.tf
- security/iam-roles-qa/versions.tf
- security/iam-users-master/versions.tf
- security/org-account-assume/versions.tf
- security/org-account-context/versions.tf
- security/org-account/versions.tf
- security/org-capability-root/versions.tf
- security/ssh-keypair/versions.tf
- storage/s3-ce-cli/versions.tf
- storage/s3-eks-public/versions.tf
- storage/s3-velero-backup/versions.tf
Signed-off-by: Audun Nes <audun.nes@gmail.com>
> Update AWS provider

- .pre-commit-config.yaml
- _sub/database/postgres-restore/main.tf
- _sub/database/postgres/main.tf
- _sub/database/postgres/outputs.tf
- _sub/database/postgres/vars.tf
- _sub/database/rds-postgres-harbor/db-server-instance.tf
- For aws_db_instance use the new parameter db_name instead of name
- Re-enable tfsec
> Use update variable name for aws_db_instance

- _sub/compute/helm-kube-prometheus-stack/values/alertmanager-slack.yaml
- _sub/compute/helm-kube-prometheus-stack/values/rules.yaml
Tested with success in sandbox
> Disable InfoInhibitor alerts

- .pre-commit-config.yaml
- _sub/compute/helm-kube-prometheus-stack/main.tf
- _sub/compute/helm-kube-prometheus-stack/vars.tf
- _sub/compute/k8s-atlantis-flux-config/main.tf
- _sub/compute/k8s-atlantis-flux-config/vars.tf
- _sub/compute/k8s-crossplane-cfg-pkg/main.tf
- _sub/compute/k8s-crossplane-cfg-pkg/vars.tf
- _sub/compute/k8s-crossplane-operator/main.tf
- _sub/compute/k8s-crossplane-operator/vars.tf
- _sub/compute/k8s-fluxcd/main.tf
- _sub/compute/k8s-fluxcd/vars.tf
- _sub/compute/k8s-traefik-flux/main.tf
- _sub/compute/k8s-traefik-flux/vars.tf
- _sub/examples/podinfo/main.tf
- _sub/examples/podinfo/vars.tf
- _sub/monitoring/blackbox-exporter/main.tf
- _sub/monitoring/blackbox-exporter/vars.tf
- _sub/monitoring/fluentd-cloudwatch/main.tf
- _sub/monitoring/fluentd-cloudwatch/vars.tf
- _sub/storage/velero-flux/main.tf
- _sub/storage/velero-flux/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- Add overwrite_on_create as the default when using the github file feature
- Enable tfsec and tflint
> Add overwrite_on_create as the default when using the github file

- _sub/compute/helm-kube-prometheus-stack/main.tf
- _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
- _sub/compute/helm-kube-prometheus-stack/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
solves this https://github.com/dfds/cloudplatform/issues/1350
> enable persistance for grafana

- _sub/compute/helm-kube-prometheus-stack/main.tf
- _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
- _sub/compute/helm-kube-prometheus-stack/vars.tf
- _sub/compute/helm-kube-prometheus-stack/version.tf
- compute/k8s-services/dependencies.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- Use Grafana with OAuth integration
- Make sure kube-prometheus-stack is not depending on auth_alb
> Don't use auth_alb with Grafana. Integrate directly with MS OAuth service

- test/integration/_global/s3-bucket-velero/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Also disables prefix delegation in QA (deferred to later) and pins the AMI on the managed node group.
Ran HCLs through formatter.
> Tolerations and affinities for monitoring workloads in QA.

- azure-pipelines.yaml
Need to wait to make sure all changes to node groups have been applied before proceeding to attempt a node rollover via the old script.
> Integrate scripts to wait for node groups and auto scaling groups.

- _sub/compute/helm-atlantis/values/values.yaml
https://github.com/dfds/cloudplatform/issues/1351
> Disable autoplanning on Atlantis.

- _sub/compute/eks-nodegroup-managed/main.tf
- _sub/compute/eks-nodegroup-managed/vars.tf
- compute/eks-ec2/main.tf
- compute/eks-ec2/vars.tf
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Allows one to parallelize the rollover of nodes in each managed node group.
Description of the update behavior can be found here: https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html
> Ability to set update config on managed node groups.

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
This requires some manual steps, so QA will be paused.
> Decommission unmananged node groups/subnets in QA.

- _sub/compute/eks-nodegroup-managed/main.tf
- _sub/compute/eks-nodegroup-managed/outputs.tf
- _sub/compute/eks-nodegroup-managed/user-data.sh.tftpl
- _sub/compute/eks-nodegroup-managed/vars.tf
- _sub/compute/eks-nodegroup-unmanaged/main.tf
- _sub/compute/eks-nodegroup-unmanaged/outputs.tf
- _sub/compute/eks-nodegroup-unmanaged/user-data.sh.tftpl
- _sub/compute/eks-nodegroup-unmanaged/vars.tf
- _sub/monitoring/fluentd-cloudwatch/dependencies.tf
- _sub/monitoring/fluentd-cloudwatch/main.tf
- _sub/monitoring/fluentd-cloudwatch/vars.tf
- compute/eks-ec2/main.tf
- compute/eks-ec2/outputs.tf
- compute/eks-ec2/vars.tf
- compute/k8s-services/main.tf
Also remove support for dockershim.
> Remove dependence on container runtime.

- _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
introduced a modified version using grafana-objects repo
> kubeapi server dashboard disabled

- .github/workflows/enforce-labels.yml
- azure-pipelines.yaml
Resolves this https://github.com/dfds/cloudplatform/issues/1473
Added ignore for QA pipeline
> Enforce labels on PR

- _sub/compute/eks-nodegroup-managed/main.tf
- _sub/compute/eks-nodegroup-managed/vars.tf
- compute/eks-ec2/main.tf
- compute/eks-ec2/vars.tf
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- Validate volume types.
- QA set to use gp3.
> Ability to specify volume types for managed nodes.

- _sub/compute/helm-atlantis/values/values.yaml
Current resource requests are excessive, especially on a sandbox.
> Tune atlantis resource requests/limits.

- _sub/security/org-policy/main.tf
- _sub/security/org-policy/vars.tf
- security/org-capability-root/main.tf
Related to https://manage.statuspage.io/pages/j6cnk4jm4vfc/incidents/mxv837495ctk
> Do not attach the old policies. Keep old policies for unmanaged accounts

- _sub/compute/helm-atlantis/values/values.yaml
Related to atlantis failing to run and/or being super slow to run (30+ minutes)
> Change Atlantis resource requests and limits to fix performance and stability issue

- .pre-commit-config.yaml
- _sub/compute/k8s-atlantis-flux-config/dependencies.tf
- _sub/compute/k8s-atlantis-flux-config/main.tf
- _sub/compute/k8s-atlantis-flux-config/vars.tf
- _sub/compute/k8s-fluxcd/dependencies.tf
- _sub/compute/k8s-fluxcd/vars.tf
- azure-pipelines.yaml
- compute/k8s-services/dependencies.tf
- compute/k8s-services/main.tf
- compute/k8s-services/outputs.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- Rename all fluxcd variables ot become more explicit
- Remove variables with semi-duplicate meaning
- Remove flux_ from variable names that are not part of the Flux CD product
- Enable tfsec again
> Refactor all variables with flux_ in the name

- _sub/compute/eks-addons/dependencies.tf
This is as preparation for final EKS 1.26 update.
> Updating EKS Add-ons to support EKS 1.26

- security/org-policies/policies/RestrictivePolicy.json
Allow teams to see cost explorer again
> Update RestrictivePolicy.json to allow teams to see cost explorer

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Let renovate look up the amis.
> Fix `amiFilter`

- security/org-account-context/main.tf
Remedies for CloudWatch 3-14 controls.
> CIS monitoring controls remedies

- .github/workflows/tflint.yml
This is in relation with the issue on the board raised by Audun.
> Setup a Github Actions TFLint

- security/org-account-context/main.tf
Not documented well in the SecurityHub docs.
> Try a different metric filter to resolve CloudWatch.4 control.

- _sub/security/cloudtrail-config/main.tf
- _sub/security/cloudtrail-config/vars.tf
- _sub/storage/s3-cloudtrail-bucket/vars.tf
- security/org-account-context/main.tf
> Enable SSE with customer managed keys for CloudTrail.

- _sub/security/config-config/main.tf
- security/org-account-context/main.tf
- security/org-account-context/vars.tf
Also enables the AWS config recorders to record global resources as well.
> Enable AWS config in multiple regions.

- compute/eks-ec2/main.tf
- storage/s3-eks-public/main.tf
- storage/s3-eks-public/vars.tf
https://github.com/dfds/cloudplatform/issues/940
> Add support for S3 bucket for kubeconfig being private

- _sub/security/iam-user/main.tf
- _sub/security/iam-user/vars.tf
- security/org-account-context/main.tf
Remedy for control: https://docs.aws.amazon.com/securityhub/latest/userguide/iam-controls.html#iam-2
> Move Deploy user admin permissions from user to group.

- security/org-policies/policies/RestrictivePolicy.json
https://github.com/dfds/cloudplatform/issues/1527 and https://dfdsit.statuspage.io/incidents/hxg95tvphjfl
> Only allow non-global services from eu-central-1 and eu-west-1

- _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
- _sub/monitoring/datadog-agent-kubernetes/main.tf
- _sub/monitoring/datadog-agent-kubernetes/vars.tf
- _sub/monitoring/datadog-agent-kubernetes/versions.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Adds the DataDog Kubernetes Operator into the EKS cluster which deploys a DataDog agent
> feat: add datadog kubernetes operator/agent

- _sub/monitoring/aws-node/main.tf
- _sub/monitoring/aws-node/vars.tf
- _sub/monitoring/aws-node/versions.tf
- compute/k8s-services/main.tf
Spawned from Issue https://github.com/dfds/cloudplatform/issues/1398
> Add a service for aws-node daemonset in order to scrape its metrics to Prometheus

- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Issue https://github.com/dfds/cloudplatform/issues/1096
> Add support for prime pipeline to Atlantis

- _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
Enables npm and usm on the datadog agent
> Feat: enable datadog usm npm

- _sub/compute/helm-atlantis/main.tf
- _sub/compute/helm-atlantis/values/values.yaml
- _sub/compute/helm-atlantis/vars.tf
- Increase Atlantis ability to do parallel tasks
- Use a server arg instead of env variable for parallelisme
> Increase Atlantis parallelisme

- security/org-account/main.tf
- security/org-account/vars.tf
- Added Support for eu-west-1 region in Security Org Accounts
> aws_region_2 added for eu-west-1

- security/org-policies/policies/RestrictivePolicy.json
- [Exclude health service describe actions from core region policy.](https://github.com/dfds/infrastructure-modules/commit/65bba74e0c82bd2da7d6cfcd4a5502f9558e4636)
- [Exclude account get actions from core region policy.](https://github.com/dfds/infrastructure-modules/commit/a96aac70b6db3bfb4b5aec528b5fa5fb40fd0194)
- [Exclude AWS Config recorder from deny dissalowed services policy.](https://github.com/dfds/infrastructure-modules/commit/1e9adfd1a706824758ff32f90fa5304f18778f48)
> Reduce unauthorized noise in hardened accounts

- compute/eks-ec2/main.tf
- compute/eks-ec2/vars.tf
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
This is to make it is easier to override individual attributes within a node group depending on environment.
I also ran `hclfmt` on QA HCLs.
> Switch node group variable from list to map.

- security/org-policies/policies/RestrictivePolicy.json
> Limit denying resource explorer policies to actions which create/modify resources.

- compute/k8s-services/dependencies.tf
- compute/k8s-services/main.tf
This is related to Issue https://github.com/dfds/cloudplatform/issues/999
> Add confluent environment variable to Atlantis pod if crossplane is deployed

- security/org-account/main.tf
first round to fix aws provider and reintroduce resource explorer from eu-west-1 safely
> fix aws providers auth. remove eu-west-1 resource explorer

- _sub/monitoring/cloudwatch-alarms/log-anomaly/main.tf
- compute/k8s-services/main.tf
[Deep dive](https://github.com/dfds/cloudplatform/issues/1522)
> Modified datapoints and added slack lambda to log account

- security/org-account/main.tf
safely renable resource explorer eu-west-1 index
> re-enable resource explorer on eu-west-1

- security/org-account-context/main.tf
https://github.com/dfds/cloudplatform/issues/1711
> remove resource explorer resource in ap and ca regions

- security/org-policies/policies/RestrictivePolicy.json
Exclude from core region only policy.
> Allow DeleteAlternateContact

- _sub/security/cloudtrail-config/main.tf
- _sub/security/cloudtrail-config/vars.tf
- security/cloudtrail-master/main.tf
- security/cloudtrail-master/vars.tf
https://github.com/dfds/cloudplatform/issues/1724
> cloudtrail-config kms policy - add support for giving AWS accounts access to key

- _sub/security/security-bot/main.tf
Security Bot changes packaged here: https://github.com/dfds/security-bot/compare/1313dff7ec07b951983220e1942f4182ae32e74c..3b2027a2c6522a03b01abd64eaa2706a87a85d4b
> Add automated folows up and escalation to the Security Bot.

- security/org-policies/policies/IntegrityPolicy.json
Related to Issue https://github.com/dfds/cloudplatform/issues/1825
> Allow EKSAdmin role to clean-up flow logs

- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- Turn off kyverno by default
- Upgrade some helm charts
> Disable Kyverno by default and upgrade Helm charts

- _sub/security/aws-backup/vars.tf
- security/org-account-context/vars.tf
> Fix aws backup vars

- security/org-policies/preventive.tf
Renamed the SID for easier reading.
> Rename SID with a capital letter for easy reading.

- _sub/security/org-delegated-administrator/main.tf
- _sub/security/org-delegated-administrator/vars.tf
- _sub/security/org-delegated-administrator/versions.tf
- security/org-delegated-administrator-master/main.tf
- security/org-delegated-administrator-master/providers.tf
- security/org-delegated-administrator-master/vars.tf
- security/org-delegated-administrator-master/versions.tf
Add support for delegated administrator
https://github.com/dfds/cloudplatform/issues/1962
> Add support for delegated administrator

- .github/workflows/housekeeping.yml
Adding housekeeping shared action for resetting repo settings back to company best practices.
[#1935](https://github.com/dfds/cloudplatform/issues/1935)
> Added housekeeping github action

- security/org-account-assume/main.tf
- security/org-account-assume/providers.tf
- security/org-account/main.tf
- security/org-account/vars.tf
> Add resource explorer to non-capability/non-legacy

- security/legacy-account-context/main.tf
> Add resource explorer to legacy-account-context

- _sub/database/postgres/main.tf
> Fix engine_family local

- _sub/database/postgres/main.tf
- _sub/database/postgres/vars.tf
- _sub/security/ssm-parameter-store/main.tf
- _sub/security/ssm-parameter-store/vars.tf
- database/postgres/main.tf
- database/postgres/vars.tf
> Allow passing tags to postgres submodule

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Upgrade control plane to 1.28 in QA

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Use AMI for 1.28

- _sub/storage/s3-bucket/main.tf
> Supress tfsec warnings on bucket that is by design public

- compute/k8s-services/vars.tf
Enforcing new pod security standards. We do not have any active blaster services running so this is purely in case we choose to have some in the future.
[2088](https://github.com/dfds/cloudplatform/issues/2088)
> Enforcing new pod security standards

- _sub/compute/helm-kube-prometheus-stack/values/prometheus.yaml
Adding a new enpoint for Prometheus where to scrap data from.
Request coming from TopDesk ticket 23106438 - data platform.
> Adding a new endpoint for Prometheus.

- _sub/compute/helm-kube-prometheus-stack/values/prometheus.yaml
Reverts dfds/infrastructure-modules#1167
> Revert "Adding a new endpoint for Prometheus."

- _sub/security/aws-backup/main.tf
- _sub/security/aws-backup/vars.tf
- security/org-account-context/main.tf
- security/org-account-context/vars.tf
> Add another backup vault

- security/legacy-account-context/main.tf
> Fix legacy-account-context

- README.md
> Document how to find compatible AMI images

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Use latest version of Atlantis image in QA testing
https://github.com/dfds/cloudplatform/issues/2243
> Use latest version of Atlantis image in QA testing

- security/org-policies/preventive.tf
- security/org-policies/vars.tf
> Allow creating g4dn.12xlarge instances

- compute/k8s-services/dependencies.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Load secrets dynamically
https://github.com/dfds/cloudplatform/issues/2353
> load secrets dynamically for Confluent Metrics scraper

- security/org-policies/preventive.tf
Updated the list to prevent spinning up expensive ec2 instances.
Based on issue https://github.com/dfds/cloudplatform/issues/2273
> Updated expensive ec2 instance types prevention.

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Upgrade Flux Helm chart to latest minor version.
https://github.com/dfds/cloudplatform/issues/2384
> Upgrade Flux in QA to latest version

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Update Atlantis helm chart in QA to 4.18.0
https://github.com/dfds/cloudplatform/issues/2394
> Update Atlantis helm chart in QA to 4.18.0

- _sub/network/acm-certificate-san/providers.tf
- _sub/network/acm-certificate-san/vars.tf
- compute/ecr-repo/providers.tf
- compute/ecr-repo/vars.tf
- compute/eks-ec2/providers.tf
- compute/eks-ec2/vars.tf
- compute/k8s-services/providers.tf
- compute/k8s-services/vars.tf
- database/postgres-restore/providers.tf
- database/postgres-restore/vars.tf
- database/postgres/providers.tf
- database/postgres/vars.tf
- network/route53-sub-zone/providers.tf
- network/route53-sub-zone/vars.tf
- storage/s3-ce-cli/providers.tf
- storage/s3-ce-cli/vars.tf
- storage/s3-eks-public/providers.tf
- storage/s3-eks-public/vars.tf
- storage/s3-velero-backup/providers.tf
- storage/s3-velero-backup/vars.tf
- test/integration/account.tfvars
> Add support for tagging policy in compute, database, network and storage

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- test/integration/hooks/custom_hook_01.sh
> Upgrade kube-prometheus-stack in QA

- security/cloudtrail-master/providers.tf
- security/cloudtrail-master/vars.tf
- security/iam-identity-center-master/providers.tf
- security/iam-identity-center-master/vars.tf
- security/iam-roles-master/providers.tf
- security/iam-roles-master/vars.tf
- security/iam-roles-qa/providers.tf
- security/iam-roles-qa/vars.tf
- security/iam-users-master/providers.tf
- security/iam-users-master/vars.tf
- security/legacy-account-context/providers.tf
- security/legacy-account-context/vars.tf
- security/org-account-assume/providers.tf
- security/org-account-assume/vars.tf
- security/org-account-context/providers.tf
- security/org-account-context/vars.tf
- security/org-account/providers.tf
- security/org-account/vars.tf
- security/org-capability-root/providers.tf
- security/org-capability-root/vars.tf
- security/org-delegated-administrator-master/providers.tf
- security/org-delegated-administrator-master/vars.tf
- security/org-policies/providers.tf
- security/org-policies/vars.tf
- security/ssh-keypair/providers.tf
- security/ssh-keypair/vars.tf
Add support for tagging policy in security modules used by our security pipelines.
https://github.com/dfds/cloudplatform/issues/2306
> Add support for tagging policy in security modules

- .github/workflows/block-on-hold-prs.yml
- .github/workflows/housekeeping.yml
Automatically block PR's that have the label 'on-hold'
[2386](https://github.com/dfds/cloudplatform/issues/2386)
> Enable block on-hold pr

- security/legacy-account-context/main.tf
- security/legacy-account-context/vars.tf
- security/org-account-context/vars.tf
> Forgot to make the changes to legacy-accounts :-)

- .github/workflows/block-on-hold-prs.yml
> Fix block-on-hold-prs github action

- compute/k8s-services/vars.tf
> Add default null to avoid validation error on plan

- security/org-account/vars.tf
Bugfix to add some defaults
https://github.com/dfds/cloudplatform/issues/2626
> Add defaults for OIDC

- security/org-policies/restrictive.tf
> Add missing brackets

- compute/k8s-services/dependencies.tf
- compute/k8s-services/vars.tf
I would like to add atlantis to https://github.com/dfds/grafana-cloud-environments and need to pass the grafana cloud API key
> Add atlantis var

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Bump k8s version to 1.29 on QA to prepare for upgrade
https://github.com/dfds/cloudplatform/issues/2530
> bumped k8s version to 1.29

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Upgrade QA to prepare to upgrade Hellman to 1.29.  
https://github.com/dfds/cloudplatform/issues/2530
> updated ami and renovate settings for QA for upgrading to 1.29

- _sub/network/vpc-flow-log/vars.tf
- _sub/security/hardened-account/main.tf
> Set VPC Flow log retention to retention_in_days

- _sub/network/vpc-peering-requester/main.tf
Adds the prerequisites for SSM session support to RDS databases
> feat: add ssm prerequisites

- _sub/monitoring/helm-grafana-agent/main.tf
- _sub/monitoring/helm-grafana-agent/values/values.yaml
- _sub/monitoring/helm-grafana-agent/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- test/integration/suite/ebs_csi_driver_test.go
- test/integration/suite/fluentd_test.go
- test/integration/suite/kube_proxy_test.go
- test/integration/suite/vpc_cni_driver_test.go
Add support for taints, tolerations and node affinity for the grafana-agent
https://github.com/dfds/cloudplatform/issues/2711
> Add support for taints, tolerations and node affinity for the grafana-agent

- _sub/compute/helm-atlantis/versions.tf
- _sub/compute/helm-crossplane/versions.tf
- _sub/compute/helm-goldpinger/versions.tf
- _sub/compute/helm-kube-prometheus-stack/version.tf
- _sub/compute/helm-kyverno/versions.tf
- _sub/compute/helm-nvidia-device-plugin/versions.tf
- _sub/monitoring/helm-grafana-agent/versions.tf
- compute/k8s-services/versions.tf
Reverts dfds/infrastructure-modules#1351
> Revert "chore(deps): update terraform helm to ~> 2.13.0"

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> Use latest version of Atlantis

- security/org-policies/restrictive.tf
> Allow changing supportplans if done by OrgRole

- _sub/security/steampipe-audit/versions.tf
- security/org-account-assume/main.tf
- security/org-account-assume/vars.tf
- security/org-account/main.tf
- security/org-account/vars.tf
Adds steampipe role to org-account and org-account-assume
> feat: add steampipe to org-account and org-account-assume

- renovate.json
Makes changes to the renovate config after update
> fix: renovate config update

- compute/k8s-services/dependencies.tf
- compute/k8s-services/vars.tf
> Add atlantis vars

- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
attempt Fix timeout issue . context https://dfds.visualstudio.com/CloudEngineering/_build/results?buildId=691696&view=results
-
> enable passing helm install timeout from hcl file

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> grafana agent chart version in QA updated

- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
> Add blackbox_exporter_namespace variable

- test/integration/suite/go.mod
- test/integration/suite/go.sum
- test/integration/suite/vendor/modules.txt
- **fix(deps): update module github.com/fluxcd/pkg/apis/meta to v1.5.0**
- **Run 'go mod vendor' manually to sort out dependency issues**
> Run 'go mod vendor' manually to sort out dependency issues

- _sub/monitoring/blackbox-exporter/values/patch.yaml
Enable scraping metrics on blackbox in grafana agent
https://github.com/dfds/cloudplatform/issues/2840
> custom labels removed in blackbox

- _sub/monitoring/helm-grafana-agent/values/values.yaml
Fix node-sockets-used dashboard
[#2851](https://github.com/dfds/cloudplatform/issues/2851)
> allow all node exporter metrics

- _sub/compute/helm-goldpinger/vars.tf
- _sub/compute/helm-kyverno/vars.tf
- _sub/monitoring/helm-grafana-agent/vars.tf
- _sub/security/external-secrets/vars.tf
- _sub/storage/velero/vars.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Preparing more helm chart to work with Flux and Renovate.
https://github.com/dfds/cloudplatform/issues/2673
> Avoid null pointer error in Flux by using empty string as defaut instead of null

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> Upgrade Velero to 4.4.1 in QA

- compute/k8s-services/dependencies.tf
- compute/k8s-services/vars.tf
> atlantis vars updated for grafana stack pipeline

- _sub/monitoring/goldpinger/dependencies.tf
- _sub/monitoring/goldpinger/main.tf
- _sub/monitoring/goldpinger/values/app-config.yaml
- _sub/monitoring/goldpinger/values/kustomization.yaml
- _sub/monitoring/goldpinger/values/patch.yaml
- _sub/monitoring/goldpinger/vars.tf
- _sub/monitoring/goldpinger/versions.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- Deploy Goldpinger with Flux
- Use the new official Helm chart by bloomberg.github.io instead of the deprecated Helm chart by okgolove.github.io
https://github.com/dfds/cloudplatform/issues/2859
> Deploy Goldpinger with Flux

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Enables grafana agent deployed with flux on QA
https://github.com/dfds/cloudplatform/issues/2754
> Enable grafana with flux on QA

- test/integration/hooks/custom_hook_01.sh
> Handle test cases where grafana namespace doesn't exist or lack the statefulset

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Revert to grafana agent deploy with helm in QA
https://github.com/dfds/cloudplatform/issues/2754
> Enable grafana with helm on QA

- .github/workflows/legitify.yaml
Testing out Legitify
[#1954](https://github.com/dfds/cloudplatform/issues/1954)
> Legitify POC

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Upgrade velero to 7.0.0 in QA
https://github.com/dfds/cloudplatform/issues/2886
> Upgrade velero to 7.0.0 in QA

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- test/integration/suite/fluentd_test.go
> Remove fluentd from QA

- _sub/security/hardened-account/main.tf
- _sub/security/security-bot/main.tf
- _sub/security/security-bot/vars.tf
> fix retention and permissions

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> atlantis docker image updated in qa

- _sub/compute/helm-atlantis/values/values.yaml
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> runAsUser updated on atlantis pod

- _sub/monitoring/helm-grafana-agent/values/values.yaml
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Scrape logs from k8s worker nodes including journal logs 
journal logs require updating grafana helm chart to the latest  (1.4.4)
https://github.com/dfds/cloudplatform/issues/2716
> scrape worker nodes logs

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> ensure grafana agent installed correctly in qa

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Update K8S controlplane to 1.30 in QA

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Upgrade K8S nodes til 1.30 in QA

- azure-pipelines.yaml
OpenTofu 1.8.0: Migrate from Terraform to OpenTofu
https://github.com/dfds/cloudplatform/issues/2852
> Use Docker image with opentofu for the pipeline

- _sub/security/iam-identity-center/dependencies.tf
- _sub/security/iam-identity-center/main.tf
- _sub/security/iam-identity-center/vars.tf
- security/iam-identity-center-master/main.tf
- security/iam-identity-center-master/vars.tf
> Add IAMRA permission set

- security/org-account-assume/main.tf
- security/org-account-assume/vars.tf
> Add IAMRA identity center assignment

- _sub/security/org-delegated-ipam-admin/main.tf
- _sub/security/org-delegated-ipam-admin/vars.tf
- _sub/security/org-delegated-ipam-admin/versions.tf
- _sub/security/org-delegated-ipam-admin/versions.tofu
- security/org-delegated-ipam-admin-master/main.tf
- security/org-delegated-ipam-admin-master/providers.tf
- security/org-delegated-ipam-admin-master/vars.tf
- security/org-delegated-ipam-admin-master/versions.tf
- security/org-delegated-ipam-admin-master/versions.tofu
> Add module and sub module for handling delgating IPAM admin in an organization

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Update QA SSH public key

- _sub/compute/eks-nodegroup-managed/dependencies.tf
- _sub/compute/eks-nodegroup-managed/main.tf
- _sub/compute/eks-nodegroup-managed/user-data-al2023.sh.tftpl
- _sub/compute/eks-nodegroup-managed/vars.tf
- compute/eks-ec2/main.tf
- compute/eks-ec2/vars.tf
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Allows to pick launch template that uses AL2023. Part of: https://github.com/dfds/cloudplatform/issues/2846
> Add support for AL2023

- security/org-policies/preventive.tf
One team told us they got blocked by the new SCP,an dthey have a need to create VPCs with public access. And also use Elastic IPs.
https://github.com/dfds/cloudplatform/issues/3020
- ~[ ] I have tested changes in my sandbox~
- ~[ ] I have added the needed changes in the `test/integration` folder to apply my changes in QA. [Read the guide on adding environment variables in QA](https://wiki.dfds.cloud/en/ce-private/atlantis/adding-env-vars)~
> Allow Public VPCs and Elastic IP

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Upgrade Control Plane in QA to 1.31

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Upgrade QA nodes to 1.31

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- test/integration/suite/ebs_csi_driver_test.go
- test/integration/suite/kube_proxy_test.go
- test/integration/suite/node_test.go
- test/integration/suite/vpc_cni_driver_test.go
> Remove unnecessary taints and tolerations

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
https://github.com/dfds/cloudplatform/issues/3017
> native ingress enabled for traefik in qa

- renovate.json
> Do not label major updates. Leave it to the reviewer to asses if it contains breaking changes and then label appropriatly

- azure-pipelines.yaml
> Do not run QA pipeline when updating irrelevant static files

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
> Remove unused inputs in QA

- _sub/security/iam-user/main.tf
> Changing the Deploy user tag key to be more specific.

- _sub/compute/atlantis/flux.tf
- _sub/compute/atlantis/values/kubeconfigs.yaml
- _sub/compute/atlantis/values/kustomization.yaml
> Create kubeconfig as a secret when atlantis_add_secret_volumes = true

- security/org-policies/preventive.tf
> Allow EKS pipelines to manage public buckets

- _sub/compute/druid-operator/dependencies.tf
- _sub/compute/druid-operator/main.tf
- _sub/compute/druid-operator/values/app-config.yaml
- _sub/compute/druid-operator/values/kustomization.yaml
- _sub/compute/druid-operator/values/patch.yaml
- _sub/compute/druid-operator/vars.tf
- _sub/compute/druid-operator/versions.tf
- _sub/compute/druid-operator/versions.tofu
- _sub/compute/elb-inactivity-cleanup/main.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Working on deprecating shared-manifests and instead move towards an operator model where we own the operator and the team is owning the druid cluster.
https://github.com/dfds/cloudplatform/issues/3048
> Add  support for Apache Druid Operator and fix a few tfsec issues

- _sub/compute/trivy-operator/dependencies.tf
- _sub/compute/trivy-operator/main.tf
- _sub/compute/trivy-operator/values/app-config.yaml
- _sub/compute/trivy-operator/values/kustomization.yaml
- _sub/compute/trivy-operator/values/patch.yaml
- _sub/compute/trivy-operator/vars.tf
- _sub/compute/trivy-operator/versions.tf
- _sub/compute/trivy-operator/versions.tofu
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Add Trivy Operator in order to patch it from it's vanilla settings in platform-apps
https://github.com/dfds/cloudplatform/issues/3052
> Add Trivy Operator

- _sub/monitoring/grafana/main.tf
- _sub/monitoring/grafana/values/app-config.yaml
- _sub/monitoring/grafana/values/patch.yaml
> Add support for Flux multi-tenancy in Grafana

- _sub/compute/k8s-fluxcd/main.tf
- _sub/compute/k8s-fluxcd/values/kustomization.yaml
- _sub/compute/k8s-fluxcd/values/rbac.yaml
- _sub/compute/k8s-fluxcd/values/sync.yaml
- _sub/compute/k8s-fluxcd/values/tenants.yaml
- _sub/compute/k8s-fluxcd/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
- test/integration/hooks/custom_hook_01.sh
> Add flux multitenant setup

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> Fix tenants input QA

- _sub/examples/podinfo/dependencies.tf
> Use service account in podifo

- _sub/storage/s3-cloudtrail-bucket/main.tf
Enable versioning of cloudtrail and cloudtrail logging buckets in order to be able to support replication of bucket.
https://github.com/dfds/cloudplatform/issues/3040
> Enable versioning of cloudtrail and cloudtrail logging buckets in order to be able to support replication of buckets

- _sub/storage/s3-bucket-lifecycle/main.tf
- _sub/storage/s3-bucket-lifecycle/vars.tf
- compute/k8s-services/main.tf
- compute/k8s-services/vars.tf
Add support for ALB bucket versioning and replication
https://github.com/dfds/cloudplatform/issues/3066
> Add support for ALB bucket replication

- .github/workflows/vendor-go.yml
This pull request includes a change to the `.github/workflows/vendor-go.yml` file to improve the verification of the test suite vendoring process.
Workflow improvement:
* [`.github/workflows/vendor-go.yml`](diffhunk://#diff-b9e163c79131fc83522873843b515d3094d00773af659d4acd00cfd08b8795b3L48-R51): Modified the script to use `md5sum` for computing checksums of `checksum-before.txt` and `checksum-after.txt` files, and updated the comparison logic to check for differences in these checksums.
https://github.com/dfds/cloudplatform/issues/3039
> Fix problem with exit code on diff

- .pre-commit-config.yaml
> Update pre-commit check. Replace tflint and add checkov

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Upgrades qa control plane to 1.32
https://github.com/dfds/cloudplatform/issues/3140
> Upgrade qa control plane to 1.32

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Upgrade QA nodes to 1.32
https://github.com/dfds/cloudplatform/issues/3140
> Upgrade qa nodes to 1.32

- security/org-account-context/dependencies.tf
This pull request includes updates to the IAM policy documents in the `security/org-account-context/dependencies.tf` file to support OIDC (OpenID Connect) authentication. The most important changes involve adding a new local variable for the OIDC issuer and updating the policy document to allow assuming roles with web identity.
Updates to support OIDC authentication:
* [`security/org-account-context/dependencies.tf`](diffhunk://#diff-8819bf6618b724a1d32e7e9cbfcf39a620d199f4a4030ef9ea536c15475ee34fR39-R42): Added a new local variable `oidc_issuer` to store the trimmed OIDC provider URL.
* [`security/org-account-context/dependencies.tf`](diffhunk://#diff-8819bf6618b724a1d32e7e9cbfcf39a620d199f4a4030ef9ea536c15475ee34fR52-R72): Updated the `shared_role_cap_acc` policy document to include a …
> Add support for IRSA fetching of your own secrets

- _sub/compute/eks-nodegroup-managed/main.tf
- _sub/compute/eks-nodegroup-managed/user-data.sh.tftpl
- _sub/compute/eks-nodegroup-managed/vars.tf
- compute/eks-ec2/main.tf
- compute/eks-ec2/vars.tf
> Add support for optional login to Docker Hub

- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> Upgrade Flux CD in QA

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
> feat: add qa nat gateways

- .trunk/trunk.yaml
- azure-pipelines.yaml
- src/qa-test-eks.sh
- test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
This pull request introduces several updates related to dependency version upgrades, environment variable renaming, and adjustments to `terragrunt` command-line arguments. Below is a summary of the most important changes:
* Updated various linting and scanning tools in `.trunk/trunk.yaml`, including `checkov`, `golangci-lint2`, `tflint`, `trufflehog`, and `yamllint` to their latest versions.
* Upgraded the `prime-pipeline` container image in `azure-pipelines.yaml` from version `2.1.2` to `2.2.0`.
* Updated the `atlantis_image_tag` in `terragrunt.hcl` from `2.0.4` to `2.1.0`.
* Renamed the environment variable `TERRAGRUNT_TFPATH` to `TG_TF_PATH` in both `azure-pipelines.yaml` and `src/qa-test-eks.sh`. [[1]](diffhunk://#diff-9eedc1d7d657ddb36b1105a0fffb4852f6d34e26454371f27b6e0ad1391f290eL48 …
> Upgrade pipeline images and commands

- _sub/compute/eks-addons/main.tf
- _sub/compute/eks-addons/vars.tf
- azure-pipelines.yaml
- compute/eks-ec2/main.tf
- compute/eks-ec2/vars.tf
- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
This pull request introduces support for specifying a KMS (Key Management Service) key ARN for the Amazon EBS CSI Driver in the EKS (Elastic Kubernetes Service) add-ons module. The changes include updates to variables, policy attachments, and module configurations to enable encryption using the specified KMS key.
* **KMS Key Policy for EBS CSI Driver**: Added an IAM policy (`aws_iam_role_policy`) and policy document (`aws_iam_policy_document`) to grant necessary permissions for the specified KMS key, including actions like `kms:Encrypt`, `kms:Decrypt`, and `kms:CreateGrant`. This is conditionally created based on whether `ebs_csi_kms_arn` is provided. (`_sub/compute/eks-addons/main.tf`, [_sub/compute/eks-addons/main.tfR102-R142](diffhunk://#diff-a043032adae754329a445c95c2ae927fcdc02359c6d7 …
> enabling adding kms for ebs encryption in eks

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Upgrades QA Kubernetes control plane to 1.33
> feat: upgrade qa control plane to 1.33

- test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Upgrades EKS nodes (kubelet) in QA to 1.33 to match control plane
> feat: upgrade qa eks nodes to 1.33

- _sub/monitoring/kafka-exporter/dependencies.tf
Priorityclassname feature added in kafka-exporter helm chart https://github.com/dfds/kafka-exporter/pull/19. This one actually uses it.
> Added priorityClassName to kafka-exporter

- .github/workflows/qa.yml
> Fix mixup of username and password for dockerhub again

- _sub/security/security-bot/main.tf
Moving providor to al2023
Updating security bot and it time the providor is updated to support the new version of go and the code.
> Update security bot main.tf to update lambda runtime

- _sub/compute/eks-cluster/eks.tf
Reverts dfds/infrastructure-modules#2026
> Revert "Change access config to API_AND_CONFIG_MAP to allow API access entries"
