dfds/infrastructure-modules

_sub/compute/k8s-blaster-configmap/main.tf

configmaps are named *.yml not *.yaml
I have changed this in the module and wish to use it in prime shortly after.

changed configmap key from yaml to yml

---

_sub/compute/eks-heptio/configmap.tf
_sub/compute/k8s-service-account/get-token.sh
_sub/compute/k8s-service-account/main.tf
_sub/compute/k8s-service-account/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Added the possibility to store kubeconfig files directly in aws parameter store. If this is merged prime needs to be updated to include an assume_role_arn for the service tfvars file to get permissions for parameter store.

Parameter store for secrets

---

_sub/compute/k8s-blaster-configmap/apply_blaster_configmap.sh
_sub/compute/k8s-blaster-configmap/main.tf
_sub/compute/k8s-blaster-configmap/vars.tf
compute/eks-ec2/main.tf

Problem with applying configmap from Blaster, seems to be due to AWS CLI runnning with AWS credentials supplied in the pipeline, not the role on the workload account it needs to assume.
Added option to shell script to assume role, and passing the role ARN to the TF module.

Added assume_role option for applying blaster configmap

---

_sub/compute/k8s-traefik/main.tf

The current annotations on the traefik service yield the following after being applied:
```yaml
apiVersion: v1
kind: Service
metadata:
annotations:
prometheus.io/port: '''8080'''
prometheus.io/scrape: '''true'''
...
```
Prometheus is not able to scrape the triple apostrophes (`'''`) for `promtheus.io/port` and `prometheus.io/scrape`.

update prometheus annotations

---

_sub/misc/kafka-message/main.tf
security/org-account-context/main.tf

I believe the heredoc had a wrongful ending by being on the same line as the context text.
If it was intended that way, please decline this.

Ended heredoc of EOF correctly on new line

---

_sub/security/org-account/main.tf

I'm tired of AWS spam in our shared mailbox.
This should be the `curl` command to opt-out of all and will be run after each account has been setup.
In this setup, it will run the command every time the module is used with a Terraform `apply` action. However, the endpoint uses to unsubscribe may not be as resilient as the AWS API we normally use, so this could theoretical make the module more fragile.
Once we're reasonably certain that we have unsubscribed from all accounts, we might consider moving the command to the "local-exec" block within the "aws_organizations_account" resource - this will cause it to only fire when creating accounts.
After merge, we should publish a new release and update `pre-prime`, `prime` and `aws-account-manifests` to use it.

Unsubscribe all accounts from AWS spam

---

_sub/compute/eks-addons/dependencies.tf
_sub/compute/eks-addons/main.tf

Previous implementation did not allow for specifying patch version of CNI, which presented a problem: https://github.com/aws/amazon-vpc-cni-k8s/issues/641.
Now:
- Able to specify x.y.z version
- Recommended VPC CNI version changed to 1.5.3

EKS: More specific VPC CNI reference, to avoid buggy AWS CNI

---

_sub/compute/k8s-traefik/main.tf

Exclude 1xx and 2xx from Traefik logs, to ease spotting errors

---

compute/ecr-repo/main.tf
compute/ecr-repo/outputs.tf
compute/ecr-repo/vars.tf

Reverts dfds/infrastructure-modules#79
Used for team self-service ECR and https://github.com/dfds/harald/blob/master/build/ecr-harald-repo/terraform.tfvars

Revert "Removed obsolete ecr-repo, because it is unused"

---

_sub/compute/eks-nodegroup-unmanaged/autoscale.tf
_sub/compute/eks-nodegroup-unmanaged/outputs.tf
_sub/compute/eks-nodegroup-unmanaged/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/outputs.tf
compute/eks-ec2/vars.tf

Adds support for second node group.
Allow passing kubelet_extra_args to ASG user data script (e.g. set node taints and labels), e.g.:
```
eks_nodegroup2_kubelet_extra_args = "--register-with-taints=gpu=true:NoSchedule --node-labels=gpu=true"
```
Which makes sense combined with GPU instance types, e.g.:
```
eks_nodegroup2_instance_types     = ["g4dn.xlarge"]
```
Tested on my existing sandbox cluster, which is similar to Hellman.

EKS: Two node groups, node taints and labels [ch1238]

---

_sub/compute/eks-nodegroup-unmanaged/autoscale.tf
_sub/compute/eks-nodegroup-unmanaged/outputs.tf
_sub/compute/eks-nodegroup-unmanaged/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/outputs.tf
compute/eks-ec2/vars.tf

* - Support for two node groups
- Allow passing kubelet_extra_args to ASG user data script (e.g. set node taints and labels)
* Minor change to test and link store [branch ch1238]
* Fixed issue where NG2 vars were required [ch1238]
Co-authored-by: janwiberg-dfds <44774288+janwiberg-dfds@users.noreply.github.com>

EKS: Two node groups, node taints and labels [ch1238] (#77)

---

azure-pipelines.yaml

Altered the pipelines to reflect changes made to replace EKS 1.13 integration test with version 1.15.
I think this is why the pipeline is failing since the integration test folder names has changed, but it wasn't reflected in the pipeline yaml.
Signed-off-by: Willi Carlsen <carlsenwilli@gmail.com>

Altered the pipelines to reflect changes in folder structure

---

test/integration/eu-west-1/k8s-qa15/cluster/terragrunt.hcl

The config map bucket was named after the previous 13 version but should be updated to reflect the new 15

Changed bucket name from 13 to 15

---

_sub/compute/eks-cluster/eks.tf
_sub/compute/eks-cluster/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf

CloudWatch log group, previously created implicitly by enabling EKS logging, is now explicitly created.
This has enabled specifying log retention, which, along with log types, have now been exposed as variables.

EKS log types and retention exposed as vars [ch1724]

---

_sub/compute/eks-nodegroup-unmanaged/dependencies.tf
_sub/compute/eks-nodegroup-unmanaged/main.tf
_sub/compute/eks-nodegroup-unmanaged/outputs.tf
_sub/compute/eks-nodegroup-unmanaged/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/outputs.tf
compute/eks-ec2/vars.tf

This release will now deploy a separate auto-scaling group per availability zone, to better control node distribution.
This means changes to some of the input variables to the `/compute/eks-ec2` main module:
| Before | After |
| --- | --- |
| eks_nodegroup1_desired_capacity | eks_nodegroup1_desired_size_per_subnet |
| eks_nodegroup1_max_size | eks_nodegroup1_max_size_per_subnet |
| eks_nodegroup2_desired_capacity | eks_nodegroup2_desired_size_per_subnet |
| eks_nodegroup2_max_size | eks_nodegroup2_max_size_per_subnet |
Taking advantage of unused node group 2.
**1. Ensure infrastructure is up-to-date and nodes are labeled:**
- In `cluster/terragrunt.hcl`, ensure `eks_nodegroup1_kubelet_extra_args` and `eks_nodegroup2_kubelet_extra_args` set a node group label, by setting value to …

EKS: Separate ASG per AZ [ch1136]

---

_sub/monitoring/cloudwatch-alarms/alb-5XX/vars.tf

This alert is way to noisy, because we have both prod and dev, staging, uat etc. environment deployed by the teams. This tends to create a lot of noise in terms of our alerts and we need to raise the threshold to account for this high level of noise.

Increase check threshold for 5XX cloudwatch alert to lower noise

---

_sub/security/iam-policies/main.tf
compute/eks-ec2/main.tf

Don't worry to much about the aws role. It is a placeholder until we get it defined.

First draft of Kubernetes clusterrole for CloudEngineer

---

_sub/compute/k8s-kiam/main.tf
_sub/compute/k8s-kiam/vars.tf
compute/k8s-services/main.tf

Parameterised several settings related to KIAM liveness and readiness probes.
Set defaults in sub-module do those of the Helm chart, added opinionated overrides on k8s-services main module (namely deep agent liveness probe, and agent liveness timeout of 5 sec).

Eks kiam probes

---

compute/k8s-services/vars.tf

The feature toggles for alarm notifier modules were incomplete, and required variables to be defined.
Setting all to a default of 'false'.

Default alarm notifier modules deploy to false (feature toggle)

---

azure-pipelines.yaml

Prime pipeline docker image updated to v0.5.2 to increment Terragrunt and Terraform versions for testing in QA.

Update prime pipeline docker image

---

azure-pipelines.yaml

This updates the prime-pipeline image in the integration tests pipeline from 0.5.3 to 0.5.4 which replaces the helm2 executable with helm3

update pipeline container image

---

_sub/compute/helm-goldpinger/main.tf

We need to add tolerations to Goldpinger in order to make sure it runs on all nodes.

Added tolerations to goldpinger

---

_sub/compute/helm-goldpinger/main.tf

https://helm.sh/blog/new-location-stable-incubator-charts/
See above URL. Relevant change made with this PR

update goldpinger helm repo from obsolete url

---

_sub/compute/helm-metrics-server/main.tf
_sub/compute/helm-metrics-server/values/values.yaml
_sub/compute/helm-metrics-server/vars.tf
_sub/compute/helm-metrics-server/versions.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This PR adds a metrics-server submodule to allow our metrics-server to be managed in state/pipeline, which it currently is not

Add helm metrics-server

---

_sub/compute/helm-kube-prometheus-stack/values/alertmanager-slack.yaml

Removed AggregatedAPIDown alert silence (null receiver) from Prometheus. Silence is no longer required after upgrade to Kubernetes 1.18

removed aggregatedapidown alert silence

---

_sub/compute/eks-alb-auth/main.tf
_sub/compute/eks-alb/main.tf

When scalling down ASGs during maintenance, there's a 5 minute delay for each ASG, meant to allow connections to train from the ALB.
However the maintenance process itself drains the workload from the nodes before triggering a scale-in operation, so it seems pointless to wait an arbitrary 5 minutes after. This reduces the delay to 0 seconds, which should remove quite a bit of overhead from the process.
Verify in sandbox cluster.

Set target group dereg delay to zero

---

compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf

Together with Rasmus we added some locals to the Terraform code to allow us to support multiple roles being annotated on the kube-system namespace.

Added locals to allow multiple roles to be assumed from kube-system

---

_sub/compute/k8s-annotate-namespace/main.tf

Needed to add single quotes to kubectl command as annotations may now include the pipe delimiter.
The absence of the quotes was causing the pipeline to fail.  This should resolve the issue.

Needed to add single quotes to kubectl command

---

compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This PR makes the Atlantis variable names less generic in computer/k8s-services to avoid potential conflicts or lack of clarity when using other modules

make atlantis variable names less generic

---

_sub/compute/helm-crossplane/main.tf
_sub/compute/helm-crossplane/values/values.yaml
_sub/compute/helm-crossplane/vars.tf
_sub/compute/helm-crossplane/versions.tf
azure-pipelines.yaml
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This PR adds a [Crossplane](https://crossplane.io/ ) module that can be toggled on and off and allows for the installation of Crossplane provider packages if any are specified

Add Crossplane module

---

_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/values/values.yaml
_sub/compute/helm-atlantis/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

- add flux github token for atlantis
- fix creation of env vars to match atlantis_ prefix var name changes
- set defaults for values that end up as env vars to empty string to avoid errors if left absent (i.e if flux is disabled you do not need to set the flux github token for flux)
- remove duplicate vars in submodule to be consistent with other submodules

Fix atlantis for flux

---

test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl

- uncomment kube-prometheus-stack for qa
- explicitly set gp2 storageclass as per prod to prevent identified issue with deletion

readd prometheus-stack to qa

---

_sub/compute/helm-goldpinger/main.tf
_sub/compute/helm-goldpinger/vars.tf
compute/k8s-services/main.tf

- add depends_on to kiam module
- remove true hardcode from goldpinger
This PR adds a depends_on to the kiam module which will deploy a servicemonitor if prometheus_stack is deployed, and deploy after prometheus_stack. The depends_on is ignored if prometheus_stack is not deployed. Goldpinger now follows the same behaviour rather than always trying to deploy a servicemonitor, now it will only use one if prometheus_stack is deployed

fixes for servicemonitor dependencies

---

test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl

This PR enables kube-prometheus-stack in QA which should now make use of the servicemonitor dependency fix

enable kube-prometheus-stack in qa after fix

---

test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl

This PR enables goldpinger in QA now that ServiceMonitor fixes have been implemented

enable goldpinger in qa

---

_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This PR removes the provided password from Atlantis for the webhooks it creates and instead uses random_password to generate one. This is preferable as we do not need to see or reuse this password

set atlantis module to generate webhook password

---

_sub/compute/k8s-fluxcd/main.tf
test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl
test/integration/eu-west-1/k8s-qa19/services/terragrunt.hcl

Previously a fixed timeframe delay was used but this caused failures in QA because CRDs were not fully deployed before being utilised.  This change introduces a small bash script that will cause a delay until the CRD's are in place.

Add Flux CRD delay script.

---

_sub/compute/helm-atlantis/main.tf

This PR will restrict the use of certain characters in the random_password resource that can cause issues by using override_special
For example, if `{` is the first generated character in the password it will cause the issue `Error: failed parsing key "github.secret" with value {+H8cc&y1g[%Ny2), list must terminate with '}'` so we do not want to generate this character

added special char override to random_password

---

_sub/compute/helm-crossplane/main.tf
_sub/compute/helm-crossplane/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa18/services/terragrunt.hcl
test/integration/eu-west-1/k8s-qa19/services/terragrunt.hcl

This PR adds the ability to supply a list(object) of service accounts (and their namespaces) which will add a clusterrolebinding to the appropriate crossplane clusterrole (crossplane-admin, crossplane-edit, crossplane-view)

Add crossplane rbac lists

---

_sub/compute/helm-crossplane/main.tf
_sub/compute/helm-crossplane/values/values.yaml
_sub/compute/helm-crossplane/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This PR lets you enable metrics for Crossplane using the crossplane_metrics_enabled variable set to true or false. It will default to true if crossplane is deployed

add crossplane metrics toggle

---

database/postgres/main.tf
database/postgres/vars.tf

Because:
- Sometimes a larger instance is needed
- t2 is already previous generation

Allow selecting db instance class instead of defaulting to t2 micro

---

_sub/compute/helm-kube-prometheus-stack/dependencies.tf
_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
_sub/compute/helm-kube-prometheus-stack/vars.tf
compute/k8s-services/dependencies.tf
compute/k8s-services/main.tf

This PR creates an IAM role with the required permissions to retrieve Cloudwatch metrics. It annotates the Grafana pods and monitoring namespace which is a prerequisite to allow us to remove the IAM key/secret currently set in the Cloudwatch datasource in our Grafana deployment and replace it with the SDK option which will automatically assume the created role via the pod annotation applied

Add cloudwatch iam role for grafana

---

_sub/compute/helm-kube-prometheus-stack/dependencies.tf
_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/vars.tf
compute/k8s-services/dependencies.tf
compute/k8s-services/main.tf

This PR creates the IAM role for grafana outside of kube-prometheus-stack to remove the circular dependency between kube-prometheus-stack and kiam that occurs

moved grafana iam role to own module

---

_sub/compute/k8s-kiam/main.tf
_sub/compute/k8s-kiam/vars.tf
test/integration/eu-west-1/k8s-qa19/services/terragrunt.hcl

NOT TO BE MERGED UNTIL next week.

Retire deprecated whitelist option for kiam v4

---

_sub/database/postgres/main.tf
_sub/database/postgres/vars.tf
database/postgres/README.md
database/postgres/vars.tf

After a quick chat, we decided to
1. Use the officially supported terraform rds module if possible
2. Change the approach taken to this feature to string concatenation in stead of anoter variable
--------------
Hardcoded parameter group family makes it impossible to use a db engine version >10. Therefore, I have added another parameter. The change is backwards compatible because the default is still postgres10. I've observed that engine_version is not supplied, terraform will default to the latest version, unless the parameter group is not compatible, in which case it will go for the newest version compatible.
For my use case, I will be ommitting the engine_version variable, but supply the parameter family variable. This will keep my database at the latest compatible version.
I have only …

Add parameter family variable

---

azure-pipelines.yaml
src/qa-test-eks.sh

- Provide missing region to the cleanup action
- Remove unnecessary parameters from extra_cleanup function
- Added "Velero" prefix to list of IAM roles cleaned up

Add velero role cleanup to qa script

---

_sub/compute/k8s-traefik/dependencies.tf
_sub/compute/k8s-traefik/main.tf
_sub/compute/k8s-traefik/output.tf
_sub/compute/k8s-traefik/vars.tf
_sub/compute/k8s-traefik/versions.tf
compute/k8s-services/dependencies.tf
compute/k8s-services/main.tf
compute/k8s-services/outputs.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa19/services/terragrunt.hcl

**Requirements in services/terragrunt.hcl:**
```
traefik_alb_auth_deploy     = true
traefik_dashboard_deploy    = true
```
For production also another DNS alias is required:
`traefik_alb_auth_core_alias = ["build.dfds.cloud", "traefik.dfds.cloud"]`
**Logic:**
When traefik_dashboard_deploy is true, the following will happen:
- A random password will be generated. 32 characters long. Contains alphanumeric characters and symbols.
- This password will be stored as a secure string in the AWS Parameter Store.
- The password will be hashed. 
- Together with a username the hashed value of the password will be stored in a Kubernetes secret.
- This means that the clear text representation of the password can never be retrieved from the secret; only from Parameter Store.
- This Kubernetes secret is …

Ingress to Traefik. Secured by Basic Auth

---

test/integration/eu-west-1/k8s-qa19/services/terragrunt.hcl

Bump the version of crossplane and aws-provider used in QA

qa19 crossplane bump

---

_sub/compute/helm-atlantis/values/values.yaml

This PR changes the Atlantis deployment service from its default of NodePort to a ClusterIP as there is no need for it to be bound to nodes when it sits behind an ingress

change atlantis service from nodeport to clusterip

---

_sub/compute/k8s-traefik-v2/main.tf
_sub/compute/k8s-traefik/main.tf
compute/k8s-services/main.tf
compute/k8s-services/versions.tf

Currently, we use anti-affinity to ensure Traefik instances were distributed across our different availability zones. This mean:
- We can not scale the number of Traefik instances beyond the number of AZs (currently 3)
- If an AZ goes down, the Traefik instance going down with it, cannot be rescheduled to other AZs, decreasing the capacity of the Traefik service
This PR replaces pod anti-affinity with the more flexible "[Pod topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)". With this, you can use a topology to distribute pods on different AZs, while still allowing some deviation, which in turn allows all the desired instanced to be schedule-able.
On top of this, a second constraint will prevent multiple instances to be …

Traefik pod topology spread

---

_sub/compute/eks-addons/dependencies.tf
_sub/compute/eks-addons/main.tf
_sub/compute/eks-addons/vars.tf
compute/eks-ec2/main.tf

Replace null resources using `kubectl` with native [`aws_eks_addon`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon) resources.
Has the added benefit that the CNI will now be pulled from the ECR registry in the same region as cluster, instead of "us-west-2".
Minimum supported Kubernetes cluster version as of this change is 1.18.

Handle EKS add-ons with native Terraform instead of kubectl

---

azure-pipelines.yaml

Bump QA pipeline image to [0.5.10](https://github.com/dfds/prime-pipeline-docker/releases/tag/0.5.10) (no Azure CLI).

Bump pipeline image (no Azure CLI)

---

_sub/compute/eks-alb-auth/main.tf
_sub/compute/eks-alb/main.tf

Setting the deregistration delay back to its default 300s (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#deregistration_delay) in alignment with this postmortem https://github.com/dfds/postmortems/blob/master/PM2021-005%20-%20All%20services%20returning%20503%20in%20Kubernetes.md#contributing-factors

Avoid rapid ALB target group deregistation

---

_sub/compute/eks-nodegroup-unmanaged/main.tf

ASGs are deployed in the `cluster` phase. Target group and attachment to ASGs in the `services` phase.
After AWS provider bump to 3.x, this causes reconfig of ASGs on every run, where all target groups are detached, and not reattached until `services` phase has completed.
Now changes to `target_group_arns` are ignored on the ASG resource (in the `clusters` phase), as the attachment is managed in the `services` phase anyway.
See https://github.com/hashicorp/terraform-provider-aws/issues/14540.

Ignore changes to target_group_arns on ASG resource

---

_sub/compute/helm-ebs-csi-driver/main.tf

Removal of null resource used to set csi-gp2 as default storage class.  Now handled using the annotations in metadata.
Set allowVolumeExpansion to true for the csi-gp2 storage class.  Note that this only works for new clusters unless you taint the existing instance of the storage class.

Enable allow volume expansion on storage classes

---

_sub/compute/helm-atlantis/values/values.yaml
_sub/compute/helm-atlantis/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
src/qa-test-eks.sh
test/integration/eu-west-1/k8s-qa20/services/terragrunt.hcl

```
WARN[0000] 'apply-all' is deprecated. Running 'terragrunt run-all apply -input=false -auto-approve' instead. Please update your workflows to use 'terragrunt run-all apply -input=false -auto-approve', as 'apply-all' may be removed in the future!
```
Also goes for `plan-all`.
```
Warning: "organization": [DEPRECATED] Use owner (or GITHUB_OWNER) instead of organization (or GITHUB_ORGANIZATION)
```

Fix various deprecations

---

_sub/compute/ec2-keypair/main.tf

Use 'key_name_prefix' instead of 'key_name' to allow easy key pair roll-over

---

_sub/compute/k8s-traefik-flux/dependencies.tf
_sub/compute/k8s-traefik-flux/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

- Adds flag to allow test ALB's to be deployed with routing to Traefik v2 Node Ports.
- Adds version lock option for Traefik v2 Helm Chart.
-

Traefikv2 ALB config

---

_sub/compute/helm-kube-prometheus-stack/values/alertmanager-slack.yaml

This PR sends KubeletTooManyPods to the null receiver to silence alerts in the hellman-alerting channel. We are currently receiving these due to the 58 pod limit (due to ENI) on our eks node instance sizes, of which 2 nodes have triggered. We should be covered by the Node Capacity alert from Grafana if we have too many pods across the entire cluster to withstand an AZ failure so this warning alert is currently noise

Add KubeletTooManyPods warning alert to null receiver

---

azure-pipelines.yaml
src/qa-test-eks.sh

This PR fixes the issue with QA being unable to remove shared roles (i.e Velero) due to a missing region variable by passing the region through the pipeline to the shell script

Fix qa destroy shared

---

_sub/compute/eks-addons/dependencies.tf

Upgrade CNI for EKS 1.20 to v1.8.0-eksbuild.1
Upgrade CNI for EKS 1.21 to v1.9.0-eksbuild.1
Remove support for EKS 1.18

Upgrade CNI for EKS 1.20 to v1.8.0-eksbuild.1

---

_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/values/alertmanager-slack.yaml
_sub/compute/helm-kube-prometheus-stack/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

We can now get rid of and stop maintaining that long list of unwanted namespace alerts.
See example config on [alertmanager's github page](https://github.com/prometheus/alertmanager#example) to understand more in dept how it works.

Exclude all namespaced alerts not matching target namespaces feature

---

_sub/compute/k8s-traefik-flux/dependencies.tf
_sub/compute/k8s-traefik-flux/main.tf

It breaks the platform apps into multiple pieces to avoid using one parent app with sub folders (like apps/cluster/app-name(s)), because in that scenario one app with problems can kill reconciliation for all other apps under the same structure. 
Now there is one kustomization called platform-apps-sources which imports Flux sources from https://github.com/dfds/platform-apps/tree/main/sources. 
For each app in platform-apps, there will be a **appname**-helm (for installing and patching the helm chart) and a **appname**-config kustomization for changes that needs to go in AFTER the CRDs are in place. The contents in **appname**-helm and **appname**-config is created using Terraform.
So for traefik it will look like this:
```
flux get kustomizations
NAME                        	READY
apps …
```

Fix Traefik install and config race conditions

---

_sub/compute/helm-atlantis/dependencies.tf
_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/values/values.yaml
_sub/compute/helm-atlantis/vars.tf
_sub/compute/helm-atlantis/versions.tf
compute/k8s-services/main.tf

This change implements a few features regarding Atlantis security plus one technical debt.
1. Atlantis UI is getting protected by Basic Authentication in order to prevent random users on the internet accessing the Atlantis UI, and possibly releasing locks on Terraform plans related to pull requests.
2. The password for basic authenticated is automatically generated, and stored in AWS Parameter store. 
3. A hashed value of the password is also stored in a Kubernetes secret.
4. Add the username and urlencoded value of the basic auth password to the webhook payload URL. This is to ensure that authentication doesn't break from Github to Atlantis after basic authentication is added.
5. All the files in helm-atlantis were in CRLF line endings, which doesn't foster platform independency. This …

Add basic auth to Atlantis deployment

---

_sub/compute/k8s-traefik-flux/dependencies.tf
_sub/compute/k8s-traefik-flux/main.tf
_sub/compute/k8s-traefik-flux/vars.tf
_sub/compute/k8s-traefik-flux/versions.tf
_sub/compute/k8s-traefik/dependencies.tf
_sub/compute/k8s-traefik/main.tf
compute/k8s-services/dependencies.tf
compute/k8s-services/main.tf
compute/k8s-services/outputs.tf
compute/k8s-services/vars.tf

- Rename existing dashboard resources to include the "-legacy" postfix.
- Create a new access to Traefik v2 dashboard.
- When cluster is configured to use Traefik through authenticated ALB, no basic auth is configured. If configured to go through the anonymous ALB, then basic auth is added.

Prepare Traefik v2 dashboard access

---

_sub/compute/eks-nodegroup-unmanaged/main.tf
compute/eks-ec2/main.tf
compute/eks-ec2/versions.tf
compute/k8s-services/versions.tf

Remove hacks introduced to circumvent a coredns addon race condition.
Tested with success in volantis sandbox. (I did a destroy first)
Tested with success in QA20 and QA21: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=392870&view=results

Use AWS provider 3.55.0 for EC2 and k8s-services provisioning

---

_sub/network/route53-record/versions.tf
_sub/security/iam-role/versions.tf

This PR is to avoid warnings like this:
```
Warning: Provider aws is undefined
│
│   on main.tf line 210, in module "traefik_alb_auth_dns_core_alias":
│  210:     aws = aws.core
│
│ Module module.traefik_alb_auth_dns_core_alias does not declare a provider
│ named aws.
│ If you wish to specify a provider configuration for the module, add an
│ entry for aws in the required_providers block within the module.
│
│ (and 2 more similar warnings elsewhere)
```

Add missing provider config for aws

---

_sub/security/azure-app-registration/main.tf
_sub/security/azure-app-registration/vars.tf
_sub/security/azure-app-registration/versions.tf
compute/k8s-services/main.tf
compute/k8s-services/versions.tf

Includes modifications to allow the Terraform provider for AzureAD to be incremented from 1.6.x to 2.2.x.
Some variable names have also been updated in order to align them with the modified parameter names used by the new provider.

Changes for AzureAD TF provider bump to 2.2.x

---

_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/vars.tf
_sub/compute/helm-goldpinger/main.tf
_sub/compute/helm-goldpinger/vars.tf
_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/vars.tf
_sub/compute/helm-metrics-server/main.tf
_sub/compute/helm-metrics-server/vars.tf

When applying Helm charts, we have both been setting the `chart_version` variable to `null` by default, and using this redundant logic:
```hcl
version          = var.chart_version != null ? var.chart_version : null
```
This PR cleans up the redundancy, making for more readable code.

Cleanup redundant null logic

---

src/qa-test-eks.sh
test/integration/eu-west-1/k8s-qa21/services/terragrunt.hcl

This PR contains to changes to QA:
1. Adding a 'sleep 900' before deleting ENI resources. This was mentioned as a workaround in a issue related to the AWS CLI when deleting ENI.
2. The QA pipeline was out of sync with the crossplane releases used in production. So this has now been aligned.
3. Due to a bug in AzureAD provider, I have disabled the app registration in QA for now.

Fixing one QA issue and attempting to fix a second QA issue. Thirdly disable app reg

---

_sub/compute/k8s-traefik-flux/main.tf
_sub/compute/k8s-traefik-flux/vars.tf
_sub/compute/k8s-traefik/main.tf
_sub/compute/k8s-traefik/vars.tf
_sub/security/ssm-parameter-store/main.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Specifically a couple of things:
- I modified the logic so instead of assigning a default value to ssm_param_createdby we instead assign it null and then use some logic to determine what value to apply.  This now means that if a value isn't set then the createdBy tag will be set to 'ssm-parameter-store' which is the name of the module which actually creates the parameter.  The logic also means that we can set values further up the chain, so in most cases the tag will be set to either 'eks-ec2' or 'k8s-services', but this can be overridden to reflect the name of a pipeline should it be required (just set the name in the account.tfvars).
- Added createdBy tags for k8s-traefik and k8s-traefik-flux modules.

Update to tagging logic

---

_sub/compute/helm-crossplane/main.tf
_sub/compute/helm-crossplane/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Seems to work on a "fresh" cluster without any previous Crossplane installations.
Currently testing the following scenarios:

Crossplane - Use UXP release

---

_sub/compute/helm-ebs-csi-driver/main.tf
_sub/compute/helm-ebs-csi-driver/values/annotations.yaml

Previous designed used a null resource to annotate a service account and then kill the pods (to ensure the annotation was honoured).
After some discussion with Rasmus we figured out how to annotate as part of the helm deployment, thus killing off two null resources.

Refactored to remove need to kill pods.

---

_sub/database/postgres/main.tf

The engine_family variable is declared locally, but it is used as an input variable so  the pipeline fails when it runs because it doesn't find a value. This PR fixes the bug.

Use local variable in main.tf

---

_sub/compute/eks-alb-auth/main.tf
_sub/compute/eks-alb/main.tf

Ref: https://aquasecurity.github.io/tfsec/v0.63.1/checks/aws/elb/drop-invalid-headers/
For planned maintenance on Tuesday January 18.
Successful in sandbox and QA: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=430046&view=results

Use drop_invalid_header_fields = true

---

_sub/compute/helm-ebs-csi-driver/main.tf
_sub/compute/helm-ebs-csi-driver/values/values.yaml
_sub/compute/helm-ebs-csi-driver/vars.tf
_sub/security/iam-oidc-provider/main.tf
_sub/security/iam-oidc-provider/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Migrates the OIDC Provider into it's own module rather than having it included as part of the CSI EBS Driver module.

OIDC provider isolation

---

_sub/storage/velero-flux/dependencies.tf
azure-pipelines.yaml
src/qa-test-eks.sh
storage/s3-velero-backup/dependencies.tf
storage/s3-velero-backup/main.tf
storage/s3-velero-backup/vars.tf
test/integration/_global/s3-bucket-velero/terragrunt.hcl

- Replace KIAM with IRSA for Velero in both AWS IAM roles and in Flux manifests.
Tested in QA: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=440218&view=results
**Usage:**
For sandboxes, QA and other environment where ALL resources are created in ONE AWS account:
In `<sandbox>/_global/s3-bucket-velero/terragrunt.hcl`:
```
bucket_name = "<unique-bucket-name>"
eks_cluster_name = "<cluster-name>"
```
In `<sandbox>/<region>/k8s-<cluster-name>/services/terragrunt.hcl`:
```
velero_flux_deploy      = true
velero_flux_role_arn    = "arn:aws:iam::<YOUR_ACCOUNT_ID>:role/VeleroBackup"
velero_flux_bucket_name = "<unique-bucket-name-same-as-above>"
```
In production where EKS resources are in one AWS account, and Velero S3 bucket and Velero IAM role is in another account:
In …

Replace KIAM with IRSA for Velero

---

_sub/compute/k8s-blaster-namespace/dependencies.tf

Doesn't change anything for Hellman. Does make our life a whole lot easier for any cluster not named Hellman (sandbox clusters 😄 )
The variable for Hellman is set at: https://github.com/dfds/eks-pipeline/blob/75e9ed7c9bb25666fae5f6734a54b283aa7a555e/oxygen-account/eu-west-1/k8s-hellman/cluster/terragrunt.hcl#L38

Use intended variable for iam policy rather than having it hardcoded

---

_sub/compute/eks-heptio/dependencies.tf
_sub/compute/eks-heptio/kubeconfig-admin.yaml
compute/eks-ec2/main.tf

After looking at various online sources & usage of "aws eks get-token", it looks like adding the AWS region explictly may fix the issue we see in QA.
For QA logs, see run "442679" in ADO.
Sources:
https://florian.ec/blog/github-actions-awscli-errors/
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1699/files

Added region to k8s auth exec command

---

_sub/compute/k8s-fluxcd/main.tf

order to avoid ERROR: You're using an RSA key with SHA-1, which is no longer allowed.
Please use a newer client or a different key type

Update TLS encryption for Flux to use a supported alorithme in

---

azure-pipelines.yaml

QA failed because the associated pipeline is now missing some variables which are required.  I wanted to get QA running so for now i've added the needed variables and  mapped them in by updating the pipeline YAML.  This might want changing at a later date to use a variable group.

Update to fix missing variable.

---

_sub/storage/velero-flux/vars.tf
compute/k8s-services/vars.tf

This PR allows the `velero_plugin_for_aws_version` and `velero_plugin_for_csi_version` variables to pass validation if no value is specified and successfully use the default values defined. Typically useful for sandbox deployments but is general good practice
This PR allows the following:
- prevent unnecessary prompts for input values for these variables if `velero_flux_deploy` is set to false by fixing the validation rule at k8s-services level to allow no value
- set default values at k8s-services level rather than an empty string which meant that the default values that were set in the velero module were always overridden

modify validation condition on velero variable to validate default

---

_sub/compute/eks-alb-auth/main.tf
_sub/compute/eks-alb/main.tf
_sub/compute/eks-nlb/main.tf

This PR replaces the deprecated alb_target_group_arn with lb_target_group_arn in the aws_autoscaling_attachment resource

replace deprecated alb_target_group_arn param

---

_sub/storage/s3-bucket-lifecycle/main.tf

This PR replaces the deprecated `policy` argument in the `aws_s3_bucket` resource with its replacement `aws_s3_bucket_policy` resource

replace deprecated policy arg in aws_s3_bucket

---

_sub/compute/helm-ebs-csi-driver/main.tf

As of version 2.10, Kubernetes provider [now supports](https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.10.0) annotations as a separate Terraform resource, enabling the mangement of annotations that are otherwise not managed by Terraform.
This change removes a `null_resource` and dependency on the `kubectl` binary, in favour of a native provider resource.
Note: I have not been able to test this myself, as I don't currently have an environment where I can do that.

Replace null_resource and kubectl dep. with native provider resource

---

security/org-account-context/dependencies.tf
security/org-account-context/main.tf

This PR will remove the crossplane-deploy role from org-account-context in infrastructure-modules

remove crossplane-deploy role from org acc ctxt

---

_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/outputs.tf
compute/k8s-services/outputs.tf

This PR modifies the kube-prometheus-stack module to store the password in the AWS SSM Parameter store. It also increases the length of the randomly generated password

store random grafana password in param store

---

_sub/compute/helm-kube-prometheus-stack/vars.tf
compute/k8s-services/vars.tf

This PR further improves the kube-prometheus-stack module by marking the optional password variable as sensitive to ensure it is not output on a terragrunt plan if a value is provided

mark grafana_admin_password var as sensitive

---

_sub/storage/s3-bucket-object/main.tf
_sub/storage/s3-bucket-object/outputs.tf

Replaced deprecated resource 'aws_s3_bucket_object' with 'aws_s3_object', as referenced in this Terragrunt warning:
```
╷
│ Warning: Argument is deprecated
│
│   with module.eks_s3_public_kubeconfig.aws_s3_bucket_object.object,
│   on ../../_sub/storage/s3-bucket-object/main.tf line 3, in resource "aws_s3_bucket_object" "object":
│    3:   bucket  = var.bucket
│
│ Use the aws_s3_object resource instead
│
│ (and 3 more similar warnings elsewhere)
╵
```

Replaced deprecated resource aws_s3_bucket_object

---

_sub/storage/s3-bucket/main.tf
_sub/storage/s3-bucket/vars.tf
storage/s3-eks-public/main.tf
storage/s3-eks-public/vars.tf

This PR adds a toggle feature to enable/disable server side encryption on an SSE bucket. It defaults to enabled to match the current behaviour, meaning no changes to any inputs are required for existing deployments. You can now, however, optionally disable it by providing `enable_server_side_encryption = false`

added toggle for s3 bucket encryption

---

security/org-capability-root/dependencies.tf

Otherwise, a user receives permission warnings in the AWS console when inputting a new policy. This leads to confusion and support tickets.

Exempt access-analyzer:ValidatePolicy action from non-EU SCP.

---

_sub/compute/eks-addons/dependencies.tf

This PR will update the eksaddon for vpccni to the latest supported version of v1.11.2-eksbuild.1 to version v1.11.4-eksbuild.1

Updated vpccni version to v1.11.4-eksbuild.1

---

_sub/security/iam-user/main.tf
_sub/security/iam-user/outputs.tf
_sub/security/iam-user/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf
security/org-capability-root/dependencies.tf

Update IAM user module to allow for secret creds not to be automatically created when a IAM user is created,

Remove creation of deploy user credentials to move responsibility to the team

---

_sub/compute/helm-goldpinger/vars.tf
_sub/compute/helm-kube-prometheus-stack/vars.tf
_sub/compute/helm-metrics-server/vars.tf
_sub/monitoring/blackbox-exporter/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

I tried running the master version of the QA pipeline before this and it failed 2 out of 3 times by getting stuck on terminating the `monitoring` namespace because of flux finalizers not being cleared up.
Ran this branch 3 times and it succeeded each time, so I'm assuming this has improved on the flakiness:
- https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=517374&view=results 
- https://dfds.visualstudio.com/CloudEngineering/_build/results?buildId=517343&view=results 
- https://dfds.visualstudio.com/CloudEngineering/_build/results?buildId=517327&view=results 
Note the `flux-system` namespace is still not properly cleaned up on services destroy, if one wants to be able to cleanly destroy and reapply solely the service phase this still doesn't work properly and will …

Specify Flux dependencies to destroy resources in the proper order

---

_sub/security/iam-idp/main.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

Need to be able now to set the Kiam server role in the account contexts, but some of the modules do not work properly when it is not set.
This should fix that.

Remove dependence on Kiam.

---

compute/eks-ec2/vars.tf
compute/k8s-services/dependencies.tf
compute/k8s-services/vars.tf
storage/s3-eks-public/vars.tf

Related to https://github.com/dfds/cloudplatform/issues/1152
- Removed unused variables in the EKS pipeline modules, used `tflint` to detect unused variables (related https://github.com/dfds/cloudplatform/issues/1182).
- Some unused variables were introduced intentionally to avoid getting warnings about the setting of undeclared variables. To avoid these warnings I think it is better to refactor the HCLs instead of introducing such unused variables into the modules which were done in a separate PR on the eks-pipeline repo.
- Introduced a validation for a variable, we should probably utilize this more.

Removed unused variables

---

azure-pipelines.yaml
src/qa-test-eks.sh

- Optionally, allow one to reset the QA account with the `NUKE_QA` environment variable.
- Remove the now unnecessary Go install.
- Add some timeouts.
- Set explicit conditions on jobs/steps to better handle skips and cancellations.
- Combine some jobs and deploy stages for efficiency.
- Reorganize into stages

Reset QA account and other QA changes

---

renovate.json

It was producing too much noise and the PRs constantly conflict with each other on `go.mod` file.

Disable updates to indirect Go dependencies.

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Signed-off-by: Audun Nes <audun.nes@gmail.com>
This is expected to fail in QA, since there are close to 100 manual steps to run through in order to update from 33.1.0 to 44.3.0, and trying to achive this by hacking QA has proved to be counter-productive.

Use kube-prometheus-stack 44.3.0 in QA

---

_sub/compute/helm-kube-prometheus-stack/values/grafana.yaml

- Use write-ahead logging (WAL) with Grafana's embedded sqllite3 database; a feature not available until Grafana 9.4.0, which is yet to be released
- Add a TODO clause for remembering to remove using a beta image for Grafana

Enable WAL for Grafana

---

_sub/compute/eks-nodegroup-unmanaged/outputs.tf
_sub/compute/eks-nodegroup-unmanaged/vars.tf
_sub/monitoring/fluentd-cloudwatch/dependencies.tf
_sub/monitoring/fluentd-cloudwatch/main.tf
_sub/monitoring/fluentd-cloudwatch/vars.tf
compute/eks-ec2/outputs.tf
compute/k8s-services/main.tf

- Configure fluentd based on runtime
- Concatenates partial logs emitted by containerd using the fluent-plugin-concat plugin
- Validation for container runtime values
- If either of the node groups in the EKS cluster has a `dockerd` container runtime it will configure fluentd to collect from `dockerd` otherwise it will be configured to collect from `containerd`

Fluentd with containerd

---

_sub/monitoring/helm-exporter/dependencies.tf
_sub/monitoring/helm-exporter/vars.tf

With the current configuration _helm-exporter_ will scrape the cluster for Helm releases every time the /metrics endpoint is hit.
Our Prometheus instance is configured to scrape all targets every 30 seconds.
Throughout the last 6 days, this helm-exporter deployment has caused 4.39M logs lines from the kube apiserver out of a total 29.9M, or rather, 14.68%.
This PR changes the [intervalDuration setting for helm-exporter](https://github.com/sstarcher/helm-exporter/blob/b8eb96d7a2baca8f41aba1894b67c4825b392360/main.go#L55), so instead of the default value of 0, it is set to 10m. When the value of _intervalDuration_ is 0, nothing is cached and the cluster is scraped on every /metrics hit. If it's anything but 0, it will scrape the cluster, pause for the duration set, and then scrape again. …

Allow configuration of intervalDuration for helm-exporter; Sets default to 10 minutes

---

test/integration/suite/node_test.go

Prefix delegation was disabled, but this wasn't updated.

Update node max pod assertion

---

_sub/compute/eks-alb-auth/main.tf
_sub/compute/eks-alb-auth/vars.tf
_sub/compute/eks-alb/main.tf
_sub/compute/eks-alb/vars.tf

Use `for_each` to remove dependence on the order of the list of auto scaling groups.

Avoid recreating autoscaling group attachments.

---

_sub/compute/eks-alb-auth/outputs.tf
_sub/compute/eks-alb/outputs.tf
_sub/compute/eks-cluster/outputs.tf
_sub/compute/eks-inactivity-cleanup/documents/delete-eks.yaml
_sub/compute/eks-inactivity-cleanup/main.tf
_sub/compute/eks-inactivity-cleanup/vars.tf
_sub/compute/eks-inactivity-cleanup/versions.tf
_sub/compute/elb-inactivity-cleanup/main.tf
_sub/compute/elb-inactivity-cleanup/vars.tf
_sub/compute/elb-inactivity-cleanup/versions.tf
compute/eks-ec2/main.tf
compute/eks-ec2/outputs.tf
compute/eks-ec2/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl

Creates a CloudWatch alarm that aims to detect inactivity. The alarm will trigger the deletion of the EKS cluster and ELB load balancers. It will fire after a workday (excludes weekends) where sandbox ELB target groups have 0 targets. CloudWatch limits the evaluation period to 1 day so this was the best workaround to avoid triggering the inactivity clean-up due to normal activity during weekends.
To reboot the resources, one needs to first run `terragrunt apply -target=module.eks_cluster` to recreate the EKS control plane. Afterwards, run the normal `terragrunt apply`s to recreate the rest of the resources along with the ELBs.
To opt out of this clean up, use the variables
`disable_inactivity_cleanup`. Use this sparingly, not as a default.

Automated inactivity triggered EKS/ELB clean up for sandboxes.

---

_sub/monitoring/fluentd-cloudwatch/dependencies.tf

This reverts commit d2471b32ac1bbc1557d76ff2e8bb0e9d4aaf3d90.

Revert "Bumping fluentd container to v1.15 after testing. (#792)"

---

_sub/compute/helm-atlantis/values/values.yaml

We just let Atlantis use whatever CPU it needs when it needs it.
FYI: https://home.robusta.dev/blog/stop-using-cpu-limits
Sandbox evidence:

Turn off CPU limit. Let it rock

---

_sub/database/postgres-restore/main.tf
_sub/database/postgres-restore/vars.tf
_sub/database/postgres/main.tf
_sub/database/postgres/vars.tf
database/postgres/README.md
database/postgres/main.tf
database/postgres/vars.tf

Enable Postgres storage autoscaling by defining the optional `max_allocated_storage` variable, as per: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#max_allocated_storage
By default, it is set to 0, which disables autoscaling.

Enable postgres storage autoscaling

---

database/postgres/outputs.tf

if the password is sensitive, `connection_string` should be protected as well - to prevent password leak

postgres.output.connection_string: flag as sensitive

---

storage/s3-velero-backup/outputs.tf

These outputs are necessary to ingest this module as a dependency.

Add outputs to the Velero module.

---

compute/k8s-services/main.tf

When trying to override an input variable from another file a `null` is being parsed a string `"null"` so it makes it impossible to unset this variable.

Allow unsetting with blank string.

---

_sub/storage/s3-bucket-lifecycle/main.tf
_sub/storage/s3-cloudtrail-bucket/main.tf
storage/s3-velero-backup/main.tf

Applies to new S3 buckets, announced in April 2023: https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

Enable ACLs on buckets before setting ACLs.

---

security/org-capability-root/outputs.tf

This PR will allow the output of OU ID from the org-capability-root module. This allows the use of the ID from terragrunt/terraform calling the org-capability-root module so we can refer to OU's by reference rather than hard-coding strings

output id from ou in org-capability-root module

---

security/org-policies/policies/RestrictivePolicy.json

What: When creating an IAM key for a capability "Deploy" user with the attached steps while signed in as Capability, users are warned that they do not have required permission to add a tag. It does not prevent the creation of the key but a description is added and the error message might suggest to the user that they can't continue. I assume this is because AWS have changed the IAM credentials interface recently. We should stop the error from appearing
Why: So that capability users can add a description to their key(s) and are not confused about creating credentials
Log into your capability account
Browse to IAM
Select Users
Click on the user Deploy
Click on the Security Credentials tab
Under Access keys click Create access key
Select Application running outside AWS. Note the best …

Allow tagging users

---

_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/values/values.yaml
_sub/compute/helm-atlantis/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

- Move to [repo level `atlantis.yaml` config](https://www.runatlantis.io/docs/repo-level-atlantis-yaml.html)
- Make the `helm-atlantis` module more reusable by not blindly passing through variables from services
- Enable staging environment with new variables passed into services
- Removed unused variables:  `atlantis_platform_fluxcd_github_token`, `atlantis_access_key_master`, `atlantis_secret_key_master`
- Split storage of Atlantis credentials in SSM into two parts to avoid `jsonencode` (one then has to decode to use the credential)
- Switch the default storage class for Atlantis from `csi-gp2` to `csi-gp3`.
- Move away from using deprecated `orgWhitelist` in the Atlantis Helm chart
--- 
Note that one will need to remap the environment variables like so in the `atlantis.yaml` in …

Atlantis refactor and prep for staging

---

security/org-account-assume/main.tf
security/org-account-assume/vars.tf

This PR will allow a parent_id to be passed through to the sub_module for org-account so that the can be placed in a specific OU.
Currently the sub_module receives a variable with the ou root id as the default value but the main module does not receive or pass through a value so it will not be overridden, so this addresses that
Backwards compatible

allow setting of parent_id for org-account

---

_sub/storage/velero-flux/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Since sandbox/QA/staging environments scale down at 18 UTC, if we want to test Velero we need to be able to override the schedule time so that it happens before the node scale down.

Abillity to specify velero cron schedule.

---

security/iam-users-master/main.tf
security/iam-users-master/outputs.tf

Avoid creating this key with Terraform and storing it in the Terraform state.
Create manually from now on.

Do not create master user key.

---

_sub/monitoring/fluentd-cloudwatch/dependencies.tf

Do not merge this until Monday 01.06.2023 - be able to test more in sandbox.

FluentD bumped to latest docker image v1.16

---

_sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

What: 
Grafana 9.4.0 or higher is now available in kube-prometheus-stack, so it can be upgraded to kube-prometheus-stack-45.20.0 or higher
Why:
We are currently running kube-prometheus-stack 44.3.0, and it has been tweaked to run Grafana 9.4.0-beta1 in order to use a feature called Write-Ahead Logging, which became available in Grafana 9.4.0.

Bump from version 44 to 45

---

test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl

This is normal procedure in preparation for production upgrade.

Updating QA control plane to 1.26

---

security/org-policies/policies/RestrictivePolicy.json

Update RestrictivePolicy.json to allow Access-analyzer, teams should be able to use Access-analyzer to assist with creating Least privilege policies. Currently it is ran in us-east-1.

Update RestrictivePolicy.json to allow Access-analyzer outside the eu regions

---

_sub/security/cloudtrail-alarm/main.tf
_sub/security/cloudtrail-alarm/outputs.tf
_sub/security/cloudtrail-alarm/vars.tf
_sub/security/cloudtrail-alarm/versions.tf
_sub/security/cloudtrail-config/main.tf
_sub/security/cloudtrail-config/outputs.tf
_sub/security/cloudtrail-config/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

- Ability to route CloudTrail logs to a CloudWatch log group 
- Ability to create a metric filter and an alarm from a CloudTrail log group.
- Ability to subscribe to a CloudTrail-based alarm.
- Ability to harden an `org-account-context` with the `harden` flag and subscribe to alerts via the `hardened_monitoring_email`.
- Remedies for `CloudWatch.1` and `CloudWatch.2` CIS 1.2 monitoring controls.

CIS monitoring controls remedies

---

_sub/security/iam-identity-center-assignment/main.tf
_sub/security/iam-identity-center-assignment/vars.tf
_sub/security/iam-identity-center-assignment/versions.tf
_sub/security/iam-policies/main.tf
security/org-account-assume/main.tf
security/org-account-assume/vars.tf

This adds the ability to assign sso permission set to accounts created via org-account-assume

feat: add facility to create sso permission assignments

---

_sub/security/iam-identity-center/main.tf

This is permission set will be used on hardened accounts to allow users to assume a limited role for handling support tickets.

Add SupportAccess permission set.

---

_sub/compute/eks-cluster/network.tf
security/org-account-context/main.tf

Disables egress/ingress in the default security groups for hardened accounts's VPC and the EKS cluster VPC.

Harden default security groups

---

_sub/storage/s3-cloudtrail-bucket/main.tf
security/cloudtrail-master/main.tf

Also a fix for a noisy drift notification, which repeatedly suggests the changes like the following:
```
~ resource "aws_s3_bucket_server_side_encryption_configuration" "bucket" {
- rule {
- bucket_key_enabled = true -> null
- apply_server_side_encryption_by_default {
- sse_algorithm = "AES256" -> null
}
}
+ rule {
+ bucket_key_enabled = true
}
}
```

Enable org-audit CloudWatch log group and KMS CMK key.

---

security/org-account-context/main.tf
security/org-account/main.tf

Enable resource discovery on AWS accounts in much accurate way. Much better than resource inventory! 
Adds resources index for eu-central-1
Adds resources index for eu-west-1
Adds view for resource index from eu-central-1

enable resource explorer in ou accounts

---

_sub/compute/eks-heptio/default-auth-cm.yaml
_sub/compute/eks-heptio/dependencies.tf

Allows one to use the AWS EKS console to browse Kubernetes resources.
You can see the EKS console working here:

Provide SSO role access in default aws-auth.

---

_sub/compute/eks-addons/dependencies.tf
_sub/compute/eks-addons/main.tf
_sub/compute/eks-addons/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf
test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
test/integration/hooks/custom_hook_01.sh

- Dynamic add-ons
- - Use resolve_conflicts_on_create and resolve_conflicts_on_update instead of deprecated attribute resolve_conflicts in aws_eks_addon. - Set QA to use latest versions of EKS addons

Modernize and simplify our usage of EKS add-ons

---

security/org-account-context/main.tf
security/org-account/main.tf

- Needed aws providers for all regions add.
- AWS providers except for eu-central-1 use region as part of their names
- Affects Capability accounts
- Affects System accounts

Enabe resource explorer in all available regions

---

_sub/security/security-bot/main.tf
_sub/security/security-bot/outputs.tf
_sub/security/security-bot/vars.tf
_sub/security/security-bot/versions.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

- Establishes SQS queue to buffer SNS notifications from the CIS control alarms.
- Deploys the [_Security Bot_](https://github.com/dfds/security-bot) Lambda function to consume the SQS queue, query the CloudWatch log group, and post events to a Slack channel.
- Places the Slack token into a secure SSM parameter encrypted with a KMS key which can only be decrypted by the Lambda execution role and the pipeline user managing the key.
- Allows one to set up monitoring channels with an email and/or Slack channel within hardened accounts.

Deploy Security Bot within hardened accounts.

---

_sub/security/org-account/main.tf
_sub/security/org-account/outputs.tf
security/legacy-account-context/dependencies.tf
security/legacy-account-context/main.tf
security/legacy-account-context/outputs.tf
security/legacy-account-context/vars.tf
security/legacy-account-context/versions.tf

- Avoid circular dependency and force replace on org-account after import
- Add module for handling legacy accounts
- Enable resource explorer indexes in all enabled regions

Add module for managing legacy accounts

---

_sub/security/security-bot/main.tf

The KMS key is for the Security Bot.

Allow AWS Config recorder access to metadata about KMS key.

---

_sub/security/security-bot/main.tf
_sub/security/security-bot/vars.tf
security/org-account-context/main.tf

In hardened accounts, one can recieve notifications when they access keys are older than 90 days or a user/credentials are not used for 45 days or more.
Messages can be sent via email or Slack.

Detect and report compliance changes related to access keys.

---

_sub/security/security-bot/main.tf

- Maps user ID to user name.
- Post metadata for relevant access keys as a reply to the main notification thread.

Improve messages related to access keys from Security Bot.

---

_sub/security/security-bot/main.tf

Increase timeout on Security Bot lambda.

---

_sub/storage/velero-flux/dependencies.tf

- Use the new format for the Velero helm chart
- Change provider name
- Use default name for backup storage location
- Change provider name

Change the Kustomize patch for velero to support the newer Helm chart versions

---

_sub/compute/helm-goldpinger/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

A new default version needed to be set in compute/services/vars.tf or else deployment would fail on systems where goldpinger has an old version installed from a previous helm repository

Add support for latest goldpinger. 

---

security/legacy-account-context/main.tf
security/legacy-account-context/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

This should help other accounts identify which pipeline performed the actions on their account when reviewing CloudTrail events.

Ability to specify AWS session names on account contexts.

---

_sub/monitoring/aws-resource-explorer-metrics/main.tf
_sub/monitoring/aws-resource-explorer-metrics/vars.tf
_sub/monitoring/aws-resource-explorer-metrics/versions.tf
security/org-account-context/main.tf

This PR adds a read role to access AWS resource-explorer-2 into org-account-context that can be assumed by a role in the master account

feat: add resourceexplorer-read role to org-account-context

---

_sub/compute/k8s-fluxcd/dependencies.tf

This is related to https://github.com/dfds/cloudplatform/issues/1781 which is about preparing for (and performing) upgrade of Flux CD and the Flux CD Terraform provider.

Turn off optional validation. This field is deprecated and removed in latest major version

---

_sub/security/security-bot/main.tf
_sub/security/security-bot/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

Major release because we need to specify these variables in the pipelines:
```
variable "security_bot_lambda_version" {
type = string
}
variable "security_bot_lambda_s3_bucket" {
type        = string
description = "The S3 bucket where the Security Bot Lambda package is stored."
}
```

Deploy Security Bot from S3 with versioning.

---

_sub/security/security-bot/main.tf

It now handles Slack rate limiting within the function by sleeping.
I am sure this can be done better, but this is good enough for now.

Increase Security Bot timeout

---

security/org-account-context/main.tf

Meeting this security control should be the responsibility of the individual teams.
This also adds compliance changes to this rule to the EventBridge rule which feeds into Security Bot so that it can be monitored through that.

Stop hardening the default security groups.

---

_sub/security/hardened-account/main.tf
_sub/security/security-bot/main.tf
_sub/security/security-bot/vars.tf

Utilized in version 2.0.0 to identify the account.

Set AWS account name in Security Bot instance.

---

_sub/compute/helm-kube-prometheus-stack/values/grafana-notifiers.yaml

This PR will temporarily revert to legacy Grafana alerts
It will allow us to re-import our alerts in a format we can then revert this change again to automatically upgrade them so that they are present in the new format, and then we can export them and put into source control.

fix: temporarily revert to legacy grafana alerts

---

_sub/compute/helm-kube-prometheus-stack/values/grafana-notifiers.yaml

This PR will re-upgrade Grafana to the new unified alerting again so that we can export the Alerting yaml once complete

fix: re-upgrade to grafana unified alerting

---

_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
_sub/compute/helm-kube-prometheus-stack/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

This feature toggle was added to be able to support Grafana 10 that comes with kube-prometheus-stack 48.0.0. 
Hence QA is also updated wit use kube-prometheus-stack 48.3.1 in preparation to upgrade production to the latest and greatest.

Disable serve_from_sub_path by default in Grafana

---

.github/pr-labels.yml
.github/workflows/labeler.yml
renovate.json

Renovatebot do not have sufficient AND/OR operators when it comes to matching file paths. So a different GH action was required. When we apply our own custom labels, Renovatebot cannot automerge unfortunately.
[Ops ticket](https://github.com/dfds/cloudplatform/issues/1865)

Added norelease label automation and refactored renovate configurations

---

security/org-policies/main.tf

Terraform does not remove empty spaces when transfering to JSON, resulting in some policies to be bigger than their limit. This fixes that issue.

Fixing terraform object to json issue.

---

_sub/compute/eks-heptio/apply_blaster_configmap.sh
_sub/compute/eks-heptio/main.tf

ADO Pipeline currently prints AWS creds. This PR remediates that by:
1. Remove echo of AWS creds in _sub/compute/eks-heptio/apply_blaster_configmap.sh
2. Change "set -xe" to "set -e" in _sub/compute/eks-heptio/apply_blaster_configmap.sh
3. Set quiet = true for the local-exec in _sub/compute/eks-heptio/main.tf
https://github.com/dfds/cloudplatform/issues/1883

Avoid printing AWS credentials. Also some formatting of bash script apply_blaster_configmap.sh

---

.github/pull_request_template.md

Remove Atlantis check from this PR template

---

.github/workflows/auto-release-security.yml

This is a proof of concept to check if we can have multiple releases on the same repo, but that triggers for a specific sets of paths. In this case changes to security and _sub/security should trigger a release with a security- release. 
Phase two is to check:
- Does it cause problems for downstream repos that uses renovate?
- Can donstream repos be configured to use the security- releases?
https://github.com/dfds/cloudplatform/issues/1920
Some checks not applicable.

Create a workflow to create security releases

---

_sub/database/postgres/main.tf
_sub/database/postgres/vars.tf
database/postgres/README.md
database/postgres/main.tf
database/postgres/vars.tf

Added db_backup_retention_period variable for the RDS module.

Add db_backup_retention_period variable to enable the tagging policy

---

security/org-policies/restrictive.tf

Adding the AWS Data Exchange service to the exclusion list for Data Platform to be able to use it in US-East-1.  The data source is only available there for the time being.
They will be looking into other offerings that can be restricted to EU regions.
230914386 - Permissions issue with AWS Data Exchange

Allow AWS Data Exchange service in us-east-1

---

_sub/monitoring/datadog-agent-kubernetes/vars.tf
compute/eks-ec2/vars.tf

- Remove unused variable cluster_agent_image_version
- Remove unused variable node_agent_image_version
- Remove unused variable interval_duration
- Remove unused variable eks_worker_subnets

Remove unused variables

---

_sub/database/postgres-restore/main.tf
_sub/database/postgres-restore/vars.tf
_sub/database/postgres/main.tf
_sub/database/postgres/vars.tf
database/postgres-restore/main.tf
database/postgres-restore/vars.tf
database/postgres/main.tf
database/postgres/vars.tf

- RDS is still publicly accessible by default, but this can be changed now
- RDS is still publicly accessible by default, but this can be changed now

RDS is still publicly accessible by default, but this can be changed now

---

_sub/compute/helm-kube-prometheus-stack/dependencies.tf

This PR adds a new notification policy to Grafana for alerts. To use you add a label to your alert of "repeat" = "24h" and the alert will use this notification policy and repeat on a 24h interval instead of the default 4h
Required for https://github.com/dfds/cloudplatform/issues/1816 and https://github.com/dfds/cloudplatform/issues/2116

feat: add a 24h repeat interval grafana alert notification policy

---

_sub/storage/external-snapshotter/dependencies.tf
_sub/storage/external-snapshotter/main.tf
_sub/storage/external-snapshotter/vars.tf
_sub/storage/external-snapshotter/versions.tf
_sub/storage/velero-flux/dependencies.tf
compute/k8s-services/main.tf

Currently we do not have support for snapshot backups of persistent volumes through Velero.
THIS PR MUST BE MERGED AFTER ANOTHER PR: https://github.com/dfds/platform-apps/pull/28
It will also FAIL in QA before the above PR is merged.
https://github.com/dfds/cloudplatform/issues/1979

Add support for snapshot.storage.k8s.io/v1 API

---

compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Add variable, so it is possible to use the feature for taking EBS volume snapshots with Velero

Add option to use Velero for creating snapshot backups of EBS volumes

---

compute/k8s-services/vars.tf

terraform-cleaner found that velero_bucket_name is no longer used in computer/k8s-services after Velero refactoring
None

Remove unused variable velero_bucket_name

---

test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
test/integration/suite/ebs_csi_driver_test.go
test/integration/suite/fluentd_test.go
test/integration/suite/kube_proxy_test.go
test/integration/suite/vpc_cni_driver_test.go

Upgrading from m5a to m6a is now super cheap with only a 0.0012 increase in cost per hour. 
At the same time, I have limited GPU nodes to 1 region instead of 3 in order to save cost in QA.
TopDesk: https://dfds.topdesk.net/tas/secure/mango/window/3?t=1699871544465

Use m6a instance family for regular workloads. Only use GPU nodes in one region to save cost

---

_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/values/prometheus.yaml
_sub/compute/helm-kube-prometheus-stack/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Enable adding config for job in prometheus to scrape metrics from confluent cloud.
Job can be configured with the followings:
- Flag to enable/disable scraping from metrics endpoint on Confluent Cloud
- Supply credentials
- List of Kafka resorces (clusters)
- Scrape interval
- Scrape timeout 
https://github.com/dfds/cloudplatform/issues/2353

job config for scraping confluent cloud prometheus metrics added

---

_sub/security/aws-backup/main.tf
_sub/security/aws-backup/vars.tf
security/org-account-context/main.tf

As the last retore points are expiring from the old dfds-vault for AWS Backup, changing our code to remove the kms and old vault.
https://github.com/dfds/cloudplatform/issues/2240

Removing ckms and old dfds-vault in AWS Backup.

---

security/org-account-context/main.tf
security/org-account-context/vars.tf

This change populates OIDC URL info in the parameter store and thus enables automation
none but related PR from https://github.com/dfds/aws-modules-rds is mentioned below

add parameter store item for oidc provider

---

database/postgres/vars.tf

As the `tags` variable was defined multiple times for the postgres module, using the module would fail with the error `Duplicate variable declaration`.
None.
- **I don't have permissions to see this guide - is this something internal for Cloud Engineering?**
**- This could go into a `patch` release. `release:patch` is not a valid git tag name. So can't tag my branch with this.. Is this a GitHub label instead?**

Remove duplicate tags variable declaration for postgres

---

_sub/database/postgres/main.tf

In the postgres module the tag `dfds.env` is automatically set to `environment`.
`dfds.env` is part of the required tags from DFDS' tagging policy: https://wiki.dfds.cloud/en/playbooks/standards/tagging_policy
None.

Set tag dfds.env from environment for postgres

---

security/org-policies/restrictive.tf

This PR removes the restriction for making S3 Multi-Region Access Points. As we restrict creation of buckets to our supported regions there is no need for this restriction.
- [ N/A ] I have tested changes in my sandbox

feat: allow s3 multiregionaccesspoint

---

_sub/compute/k8s-fluxcd/dependencies.tf
_sub/compute/k8s-fluxcd/main.tf
_sub/compute/k8s-fluxcd/vars.tf
compute/k8s-services/dependencies.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This PR will allow for application deployments via PR's into a "custom" folder inside our flux manifests repository per cluster.
Simply create a folder inside your "platform-apps/[cluster-name]/custom" folder with some Kubernetes manifests and they will be automatically deployed.
I.e to deploy an application called "test-app" into the "cluster1" k8s cluster, in the flux mainfests repo create a folder at "platform-apps/cluster1/custom/test-app" and in there place your "deployment.yaml"

feat: support custom flux deployments

---

_sub/compute/k8s-fluxcd/dependencies.tf
_sub/compute/k8s-fluxcd/vars.tf
compute/k8s-services/dependencies.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Remove some variables and flux git repository accidentally left in the flux module

fix: remove unused flux repo and vars accidentally left in

---

_sub/monitoring/helm-grafana-agent/main.tf
_sub/monitoring/helm-grafana-agent/values/values.yaml
_sub/monitoring/helm-grafana-agent/vars.tf
_sub/monitoring/helm-grafana-agent/versions.tf
azure-pipelines.yaml
compute/k8s-services/dependencies.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

- Add sub module for installing Grafana Agent in Kubernetes using Helm.
- Install Grafana Agent in Kubernetes using Helm
- Mark the Grafana Cloud API token variable as sensitive
- Enable Grafana Agent in QA
https://github.com/dfds/cloudplatform/issues/2502

Add Grafana Agent

---

security/org-policies/restrictive.tf

During a capability deletion process I identified that a policy change was needed in order to be able to delete the AWS account using the root account.

This is to allow accounts to be deleted using root on capability deletion process.

---

_sub/security/iam-github-oidc-provider/main.tf
_sub/security/iam-github-oidc-provider/vars.tf
security/org-account/main.tf
security/org-account/vars.tf

This feature will create an OIDC provider for Github, an IAM policy and an IAM role that can be used to trust between AWS and GitHub Actions, so Terraform/Terragrunt on GitHub Actions can save state and locks on AWS.
https://github.com/dfds/cloudplatform/issues/2626

Add support for OIDC trust with GitHub for Terraform/Terragrunt

---

_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

In order to add synthetic checks for atlantis in grafana cloud, I need to pass the username and password for atlantis. This PR enables creating these as organization secrets on github.

Add GitHub org secret for atlantis

---

_sub/network/route-table/main.tf

We need to replace the inline route list on the route table with use of the route resource instead so we can add routes via the vpc peering automation where required.
See the note on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table about why using the inline route and route resource together is a conflict
I have tested with my sandbox and this results in a straight swap/adoption of the only record (default route) by the new resource. As there was a lifecycle rule to ignore_changes no other routes are managed by state so are left alone.
I cannot see the route-table module being used elsewhere where this might have an undesired effect but would appreciate another set of eyes to confirm

fix: migrate from inline default route to individual route resource

---

_sub/security/grafana-cloud-cloudwatch-integration/main.tf
_sub/security/grafana-cloud-cloudwatch-integration/outputs.tf
_sub/security/grafana-cloud-cloudwatch-integration/vars.tf
_sub/security/grafana-cloud-cloudwatch-integration/versions.tf
security/legacy-account-context/main.tf
security/legacy-account-context/outputs.tf
security/legacy-account-context/vars.tf
security/org-account-assume/main.tf
security/org-account-assume/outputs.tf
security/org-account-assume/vars.tf
security/org-account-context/main.tf
security/org-account-context/outputs.tf
security/org-account-context/vars.tf

- **Create sub module for create integration between Grafana Cloud and AWS**
- **Add support for Grafana Cloud integration with Cloudwatch in capability accounts**
- **Add support for Grafana Cloud integration with Cloudwatch in legacy accounts**
- **Add support for Grafana Cloud integration with Cloudwatch for prime accounts**
https://github.com/dfds/cloudplatform/issues/2599

Add support for Grafana Cloud integration with Cloudwatch for capability, legacy and prime accounts

---

security/org-policies/restrictive.tf

We have a team that needs to be able to create identity providers in their account for setting up SSO with Redshift. We've previously denied these IAM actions because of legacy reasons(our use of ADFS), but I no longer see any reason to deny them. We don't deny creation of OIDC providers.

Removed iam:*SAMLProvider deny actions

---

_sub/monitoring/helm-grafana-agent/main.tf
_sub/monitoring/helm-grafana-agent/values/values.yaml
_sub/monitoring/helm-grafana-agent/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
test/integration/hooks/custom_hook_01.sh

Add support for stateful WAL in Grafana Agent. Also support for more than one replica.
[
https://github.com/dfds/cloudplatform/issues/2715

Add support for stateful WAL in Grafana Agent

---

_sub/network/vpc-peering-requester/main.tf
_sub/network/vpc-peering-requester/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

PR allowing us to disable the creation of vpc endpoints for vpc peering if required
Should be backwards compatible as it will automatically move the state from resource to resource[0]

feat: allow disabling of vpc endpoints for peering

---

_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/security/azure-app-registration/main.tf

Update application_object_id to application_id to comply with changes in the provider.
`The 'application_object_id' property has been replaced with the
'application_id' property and will be removed in version 3.0 of the AzureAD
provider`

Fixed deprecation

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

To avoid this error:
```
2024-04-17T02:45:10.7830867Z [31m│[0m [0m[1m[31mError: [0m[0m[1mexecution error at (k8s-monitoring/templates/kubernetes-monitoring-telemetry.yaml:1:3): 
2024-04-17T02:45:10.7831694Z [31m│[0m [0m
2024-04-17T02:45:10.7832291Z [31m│[0m [0mAs of k8s-monitoring Chart version 1.0, Grafana Agent has been replaced with Grafana Alloy.
2024-04-17T02:45:10.7832907Z [31m│[0m [0mThese sections in your values file will need to be renamed:
2024-04-17T02:45:10.7833421Z [31m│[0m [0m  grafana-agent          --> alloy
2024-04-17T02:45:10.7833876Z [31m│[0m [0m  grafana-agent-events   --> alloy-events
2024-04-17T02:45:10.7834453Z [31m│[0m [0m  grafana-agent-logs     --> alloy-logs
2024-04-17T02:45:10.7834914Z [31m│[0m [0m  grafana-agent-profiles --> …
```

Version lock Grafana

---

_sub/monitoring/helm-grafana-agent/values/values.yaml

Disable auto-deploy of kube_state_metrics exporter in grafana-agent helm because we are getting duplicated metrics. An already running instance of kube_state_metrics exporter is already deployed and running in monitoring namespace
https://github.com/dfds/cloudplatform/issues/2722
~~- [ ] I have added the needed changes in the `test/integration` folder to apply my changes in QA. [Read the guide on adding environment variables in QA](https://wiki.dfds.cloud/en/ce-private/atlantis/adding-env-vars)~~

disable kube_state_metrics exporter from grafana agent

---

_sub/compute/helm-atlantis/versions.tf
_sub/compute/helm-crossplane/versions.tf
_sub/compute/helm-goldpinger/versions.tf
_sub/compute/helm-kube-prometheus-stack/version.tf
_sub/compute/helm-kyverno/versions.tf
_sub/compute/helm-nvidia-device-plugin/versions.tf
_sub/monitoring/helm-grafana-agent/versions.tf
compute/k8s-services/versions.tf

Trying to get Atlantis working with latest version of the Terraform Helm provider after upgarding all tools. 
Issue: https://github.com/dfds/cloudplatform/issues/2774

Update terraform helm to ~> 2.13.0""

---

_sub/security/security-bot/main.tf

aws-account-manifest is broken. New accounts with `harden = true` will fail to deploy security bot lambda because Go is no longer a supported runtime.
https://github.com/dfds/cloudplatform/issues/2784

Go is no longer a supported runtime for lambdas. It must now run on Amazon Linux

---

_sub/monitoring/helm-grafana-agent/main.tf
_sub/monitoring/helm-grafana-agent/values/values.yaml
_sub/monitoring/helm-grafana-agent/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Grafana k8s chart with alloy configs to prepare for migrating to Alloy. 
Open cost metrics disabled by default
This will require that EKS-pipeline to update the `grafana_agent_chart_version` value to "1.0.7"
https://github.com/dfds/cloudplatform/issues/2773

Replace Grafana agent with alloy

---

_sub/security/steampipe-audit/main.tf
_sub/security/steampipe-audit/vars.tf
security/legacy-account-context/main.tf
security/legacy-account-context/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

This PR adds a steampipe audit role with view/read only access to accounts using org-account-context and legacy-account-context

feat: add steampipe audit role

---

security/org-account-assume/main.tf

Sets the correct AWS workload for org-account-assume's use of steampipe submodule

fix: set correct aws workload for steampipe-audit org-account-assume

---

renovate.json

This PR should enable the renovate dependency dashboard via the config:recommended preset config with a schedule to automtically raise any PR's once per week.

feat: enable renovate dependency dashboard and schedule

---

_sub/security/azuread-group/main.tf
_sub/security/azuread-group/outputs.tf
_sub/security/azuread-group/vars.tf
_sub/security/azuread-group/versions.tf

Adds a submodule for creating Azure AD group. Part of: https://github.com/dfds/cloudplatform/issues/2756

Add azuread_group submodule

---

compute/k8s-services/dependencies.tf
compute/k8s-services/vars.tf

Adds atlantis env vars needed for grafana cloud environments. Part of: https://github.com/dfds/cloudplatform/issues/2756

Add atlantis vars for grafana cloud app registration

---

_sub/compute/k8s-crossplane-operator/dependencies.tf
_sub/compute/k8s-traefik-flux/dependencies.tf
_sub/monitoring/blackbox-exporter/values/patch.yaml
_sub/monitoring/helm-exporter/values/patch.yaml
_sub/monitoring/metrics-server/dependencies.tf
_sub/security/external-secrets/dependencies.tf
_sub/storage/velero/dependencies.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

- Upgrade Flux in QA to use version 2.3.0
- It will also upgrade all CRD API versions used, and is hence a candidate for staging and production afterwards.
https://github.com/dfds/cloudplatform/issues/2810

Upgrade QA to use Flux 2.3.0

---

_sub/compute/k8s-fluxcd/providers.tf
_sub/compute/k8s-fluxcd/vars.tf
compute/k8s-services/main.tf

Use connection data from Kubernetes data source instead of kubeconfig

Use connection data from Kubernetes data source instead of kubeconfig

---

_sub/compute/helm-kube-prometheus-stack/values/components.yaml
_sub/monitoring/helm-grafana-agent/values/values.yaml

Enable kube-stats-metrics exporters to run in parallel in the 2 available namespaces
Servicemonitor for kube-stats-metrics the legacy setup running in the legacy namespace
-

re-deploy kube-prom-stats in legacy setup

---

_sub/monitoring/helm-grafana-agent/values/values.yaml

Enable full list of metrics for kube-stats and cadvisor
https://github.com/dfds/cloudplatform/issues/2838

allow lists for kube-stats and cadvisor metrics updated

---

_sub/security/eks-version-endpoint/main.tf
_sub/security/eks-version-endpoint/system-public-info-viewer.yaml
_sub/security/eks-version-endpoint/vars.tf
_sub/security/eks-version-endpoint/versions.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf

Turn off public access to the EKS cluster API version endpoint after discussions with @jdsmithit 
https://github.com/dfds/cloudplatform/issues/2842

Turn off public access to the EKS cluster API version endpoint

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Disables grafana agent on QA
https://github.com/dfds/cloudplatform/issues/2754

Disable grafana with flux on QA

---

_sub/security/iam-policies/main.tf
security/iam-roles-master/main.tf
security/iam-roles-master/vars.tf

For iam-roles-master, make iam_role_trusted_account_root_arn into a list in order to support multiple ARNs
This is to ensure not the "root" account is trusted, because that means all users, including read-only users.
https://github.com/dfds/cloudplatform/issues/1532

For iam-roles-master, make iam_role_trusted_account_root_arn into a list in order to support multiple ARNs

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

https://github.com/dfds/cloudplatform/issues/2889

Remove version locking of Velero in QA

---

_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/values/values.yaml
_sub/compute/helm-atlantis/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Adds a toggle to optionally mount volumes into Atlantis. One is predefined, must have a secret existing called kubeconfigs

feat: optionally mount kubeconfigs secret to atlantis

---

azure-pipelines.yaml

Re-enabled the test on master branch now it is unbroken

fix: re-enable master test

---

_sub/security/iam-policies/main.tf
_sub/security/iam-policies/outputs.tf
security/org-account-context/dependencies.tf
security/org-account-context/main.tf

Each account receives a role for reading VPCs and Tags.
This is assumable by the self-service API to present this information to GUI and CLI
2924
https://github.com/dfds/cloudplatform/issues/2924

Add policies and trust for reading vpc information

---

azure-pipelines.yaml
src/qa-test-eks.sh
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Upgrade Atlantis. Make usage of OpenTofu more verbose

---

_sub/compute/helm-atlantis/main.tf
_sub/compute/helm-atlantis/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

If you are using a personal token to use Atlantis with a personal repo, it would previously fail because the sub module also attempts to add the Atlantis username and password as organizational secrets. With this fix, this becomes optional, but will still be enable dby default to ensure backward compability.
None, found this bug on relevant testing.

Support Atlantis deployments for sandbox repos that are on a personal account instead of an organization account

---

_sub/network/ipam-pool/main.tf
_sub/network/ipam-pool/output.tf
_sub/network/ipam-pool/vars.tf
_sub/network/ipam-pool/versions.tf
_sub/network/ipam-pool/versions.tofu
_sub/network/ipam-scope/main.tf
_sub/network/ipam-scope/output.tf
_sub/network/ipam-scope/vars.tf
_sub/network/ipam-scope/versions.tf
_sub/network/ipam-scope/versions.tofu
_sub/network/ipam/main.tf
_sub/network/ipam/output.tf
_sub/network/ipam/vars.tf
_sub/network/ipam/versions.tf
_sub/network/ipam/versions.tofu
network/ipam/main.tf
network/ipam/providers.tf
network/ipam/vars.tf
network/ipam/versions.tf
network/ipam/versions.tofu

- **Add modules and sub modules for managing IPAM**
- **Make the IPAM modules usable**
- **Refactor IPAM pool variable**
- Create main module for using AWS IPAM and related features
- Sub module for creating IPAM
- Sub module for managing IPAM scopes
- Sub module for managing IPAM pools
https://github.com/dfds/cloudplatform/issues/2992
Proof that it is working:

Create module for managing AWS IPAM

---

network/ipam/main.tf
network/ipam/vars.tf

Add optional prefix that can be used to create uniqueness if other teams that create IPAM scopes and pools outside terraform use the same names for their resources as we do.
https://github.com/dfds/cloudplatform/issues/2992

Add the ability to prefix name and description of IPAM scope and pools

---

network/ipam/main.tf
network/ipam/vars.tf

We need to support different pipelines that uses IPAM. Some can use the native IPAM roles. Others can't because they are already in a different context.
It's a major release because the changing type of a variable breaks the only implementation we have of it.
https://github.com/dfds/cloudplatform/issues/2997

Add support for multiple roles to assume when requesting CIDR range from IPAM

---

_sub/compute/k8s-shared-manifests/values/shared-manifests.yaml

Fix problem with missing dependencies between Flux manifests in shared-manifests

---

security/org-policies/preventive.tf

Added policies to prevent users from using the old v1 of the metadata service API.
[#2991](https://github.com/dfds/cloudplatform/issues/2991)

Added IMDSv1 Preventive Policies

---

_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/versions.tf
_sub/compute/helm-kube-prometheus-stack/versions.tofu
_sub/security/azure-app-registration/main.tf
_sub/security/azure-app-registration/outputs.tf
_sub/security/azure-app-registration/versions.tf
_sub/security/azure-app-registration/versions.tofu
_sub/security/azuread-group/versions.tf
_sub/security/azuread-group/versions.tofu
compute/k8s-services/main.tf
compute/k8s-services/versions.tf
compute/k8s-services/versions.tofu

- **chore(deps): update terraform azuread to v3**
- **Make usage of azuread provider compliant with version 3**
Check the upgrade guide for v2 to v3 of azuread provider and change the use of application_id to client_id where applicable.
https://github.com/dfds/cloudplatform/issues/3021

Make usage of azuread provider compliant with version 3 of the provider

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Velero is currently not working in QA

Version lock Velero in QA to avoid runtime errors

---

_sub/security/azure-app-registration/dependencies.tf
_sub/security/azure-app-registration/main.tf
_sub/security/azure-app-registration/outputs.tf
_sub/security/azure-app-registration/vars.tf
_sub/security/azure-app-role-assignment/main.tf

Enable requesting api permissions on AzureAD app registrations
https://github.com/dfds/cloudplatform/issues/2858

api permissions on azuread app

---

_sub/storage/velero/main.tf
_sub/storage/velero/values/patch.yaml
_sub/storage/velero/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

- Add support for excluding certain resource types from backup.
- Remove CSI driver configuration for Velero. It is now included by default.
- Remove hardcoded image tag.
- Upgrade Velero Helm chart in QA
https://github.com/dfds/cloudplatform/issues/3083

Add support for excluding resource types from Velero backups

---

_sub/security/azure-app-registration/main.tf
_sub/security/azure-app-registration/vars.tf

Enable specifying groups claim in azuread app registration
Fix issue on Grafana Teams' external group sync

groups claim for oauth2 azuread applications

---

_sub/compute/helm-kube-prometheus-stack/main.tf
_sub/compute/helm-kube-prometheus-stack/outputs.tf
_sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
_sub/compute/helm-kube-prometheus-stack/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/outputs.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

In order to simplify the sunsetting of kube prometheus stack in our Kubernetes cluster, this PR adds a feature toggle for Grafana, so that the Grafana instance that comes with kube prometheus stack can be toggle off prior to sunsetting kube prometheus stack.
This pull request introduces a feature toggle for enabling or disabling Grafana deployment in the `helm-kube-prometheus-stack` module. The most important changes include the addition of the `grafana_enabled` variable, conditional logic based on this variable, and updates to outputs.
* Added `grafana_enabled` variable to control the deployment of Grafana. (`_sub/compute/helm-kube-prometheus-stack/vars.tf`, `compute/k8s-services/vars.tf`) [[1]](diffhunk://#diff-5398bbac0a94b58e045747e9ac757eaca71e4c1c9ed5b948adc6b6697433ffe9R27-R32) …

Add feature toggle for enabling/disabling Grafana in kube-prometheus-stack

---

renovate.json

This pull request includes a change to the `renovate.json` file to better manage dependencies affecting the QA environment and its test resources.
Dependency management improvements:
* [`renovate.json`](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57R87-R95): Added a new group for dependencies affecting the QA environment, including a description, matching file names, and a label to prevent release.
https://github.com/dfds/cloudplatform/issues/3049

Add label norelease to changes in the test/integration directory

---

.github/workflows/vendor-go.yml
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

This pull request includes updates to the Go module vendoring process and a version bump for Flux CD in the test suite. The most important changes include modifications to the workflow file to improve the vendoring process and ensure the test suite is correctly vendored before running tests.
Changes to the Go module vendoring process:
* [`.github/workflows/vendor-go.yml`](diffhunk://#diff-b9e163c79131fc83522873843b515d3094d00773af659d4acd00cfd08b8795b3L1-R13): Updated the workflow name and job name, added steps to find and compare checksums before and after vendoring, and ensured the test script only runs if vendoring was updated. [[1]](diffhunk://#diff-b9e163c79131fc83522873843b515d3094d00773af659d4acd00cfd08b8795b3L1-R13) [[2]](diffhunk://#diff-b9e163c79131fc83522873843b515d3094d00773af6 …

Verify that vendoring is actually taking place before compiling and commiting

---

compute/k8s-services/dependencies.tf

Cleaning up following grafana self-hosted has been disabled.

Removing monitoring-grafana.monitoring/api/health from Blacbox explorer.

---

compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf

This pull request includes changes to the `compute/eks-ec2` module to add support for overriding the version of the AWS EFS CSI driver. The most important changes include adding a new variable for the EFS CSI driver version override and updating the EKS addons configuration.
Enhancements to EKS addons configuration:
* [`compute/eks-ec2/main.tf`](diffhunk://#diff-377519e7ca2d872af5e1381cb6c57e93942c12625344ff8fc8a970e19a400742R182): Added support for `awsefscsidriver_version_override` to allow specifying a custom version for the AWS EFS CSI driver.
New variable addition:
* [`compute/eks-ec2/vars.tf`](diffhunk://#diff-b18f8354ea8f3932f1be0681155c6e70c457a10798e9be3a07994adfea3d16b3R121-R125): Introduced a new variable `eks_addon_awsefscsidriver_version_override` to hold the version override …

Add support for overriding EKS addon version for EFS. Plus formatting

---

azure-pipelines.yaml
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

This pull request includes updates to the container image versions used in the pipeline and the Atlantis image tag in the Terragrunt configuration file.
Updates to container image versions:
* [`azure-pipelines.yaml`](diffhunk://#diff-9eedc1d7d657ddb36b1105a0fffb4852f6d34e26454371f27b6e0ad1391f290eL27-R27): Updated the `prime` container image from `dfdsdk/prime-pipeline:2.1.1` to `dfdsdk/prime-pipeline:2.1.2`.
Updates to Atlantis configuration:
* [`test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl`](diffhunk://#diff-23bdbeb0d3e57bc3139b318801dda0b1c266354c34072dffc2a1932f1df0cc11L176-R176): Updated the `atlantis_image_tag` from `2.0.2` to `2.0.4`.
https://github.com/dfds/cloudplatform/issues/3142

Use latest pipeline image and Atlantis image

---

_sub/security/helm-1password-connect/main.tf
_sub/security/helm-1password-connect/vars.tf
_sub/security/helm-1password-connect/versions.tf
_sub/security/helm-1password-connect/versions.tofu
azure-pipelines.yaml
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This pull request introduces several changes to integrate 1Password Connect credentials and tokens into the infrastructure. The most important changes include adding new AWS SSM parameters, updating Terraform configurations, and modifying Azure Pipelines and Kubernetes services to support the new credentials and tokens.
* Added new AWS SSM parameters for storing 1Password Connect credentials and tokens in `_sub/security/helm-1password-connect/main.tf`.
* Introduced new variables for 1Password Connect credentials and tokens in `_sub/security/helm-1password-connect/vars.tf`.
* Added AWS provider configuration in `_sub/security/helm-1password-connect/versions.tf`.
* Added AWS provider configuration in `_sub/security/helm-1password-connect/versions.tofu`.
* Updated `azure-pipelines.yaml` to …

Create the missing credentials in 1password-connect through automation

---

_sub/storage/velero/vars.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

Update velero plugin version for AWS 
Fix the validation
[#3046](https://github.com/dfds/cloudplatform/issues/3046)

velero plugin for aws version bumped

---

_sub/network/vpc-peering-accepter/main.tf
_sub/network/vpc-peering-accepter/vars.tf

This pull request makes significant changes to the VPC peering accepter module to improve route table selection logic and ensure better flexibility. The key updates include replacing the `aws_vpc` data source with `aws_route_tables`, adding logic to select preferred or alternate route tables, and updating the `route_table_id` variable.
Changes to route table selection:
* [`_sub/network/vpc-peering-accepter/main.tf`](diffhunk://#diff-e20c94f5b3d396ae3b54981dea98d7df5621903ae9bb85c63dbbc8b0182d79ceL1-R40): Replaced the `aws_vpc` data source with `aws_route_tables` for both preferred and alternate route tables, added filters to select appropriate route tables based on tags and other criteria, and introduced local variables to determine the length of route table IDs. The `aws_route` resource …

Find route tables for VPC peering based on tags or filters

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

This pull request includes updates to the `terragrunt.hcl` file in the `test/integration/eu-west-1/k8s-qa/services` directory. The changes involve updating the Helm chart versions for both the blue and green variants of Traefik.
Updates to Helm chart versions:
* Updated `traefik_blue_variant_helm_chart_version` from "23.1.0" to "34.4.0".
* Updated `traefik_green_variant_helm_chart_version` from "20.8.0" to "34.4.0".
https://github.com/dfds/cloudplatform/issues/2791

Use Traefik version 34.4.0

---

_sub/compute/eks-nodegroup-managed/dependencies.tf
_sub/compute/eks-nodegroup-managed/main.tf
_sub/compute/eks-nodegroup-managed/vars.tf

This pull request includes several changes to the `_sub/compute/eks-nodegroup-managed` module to improve the handling of inactivity cleanup for sandbox environments. The most important changes are focused on simplifying the conditions and variables related to scaling the ASG (Auto Scaling Group) to zero.
Changes to inactivity cleanup handling:
* [`_sub/compute/eks-nodegroup-managed/dependencies.tf`](diffhunk://#diff-f453dda9d53534bdd9b8c21523bb24902f90d4b2d02250e56845d2d2b234d968L4-R4): Modified the `asg_min_size` condition to use `var.enable_inactivity_cleanup` instead of `var.eks_is_sandbox`.
* [`_sub/compute/eks-nodegroup-managed/dependencies.tf`](diffhunk://#diff-f453dda9d53534bdd9b8c21523bb24902f90d4b2d02250e56845d2d2b234d968L42-L51): Removed the local variable …

Fixed bug where no autoscaling is scheduled for sandboxes after refactoring

---

compute/k8s-services/dependencies.tf
compute/k8s-services/vars.tf

This pull request includes updates to the monitoring configuration for Traefik variants in the Kubernetes services. The main changes involve parameterizing the ports used for monitoring the blue and green variants of Traefik.
Updates to monitoring configuration:
* [`compute/k8s-services/dependencies.tf`](diffhunk://#diff-2e7c8e5dd2f4a76d76adb2da41988c1905571c7b2d401b1c58fc0f113241e49bL228-R234): Modified the URLs for `blackbox_exporter_monitoring_traefik_blue_variant` and `blackbox_exporter_monitoring_traefik_green_variant` to use the new port variables `${var.blackbox_exporter_monitoring_traefik_blue_variant_port}` and `${var.blackbox_exporter_monitoring_traefik_green_variant_port}` respectively.
New variable definitions:
* [`compute/k8s-services/vars.tf`](diffhunk://#diff-83380a112934c41 …

Add a new variable to control the port number that blackbox exporter should contact the Traefik endpoint on

---

azure-pipelines.yaml

This pull request includes a small change to the `azure-pipelines.yaml` file. The change adds Docker Hub credentials to the environment variables section.
* [`azure-pipelines.yaml`](diffhunk://#diff-9eedc1d7d657ddb36b1105a0fffb4852f6d34e26454371f27b6e0ad1391f290eR44-R45): Added `TF_VAR_docker_hub_username` and `TF_VAR_docker_hub_password` to the environment variables.
https://dfds.visualstudio.com/Cloud%20Engineering%20Team/_workitems/edit/520271

Add variables for Docker Hub credentials

---

_sub/compute/eks-nodegroup-managed/dependencies.tf
_sub/compute/eks-nodegroup-managed/main.tf
_sub/compute/eks-nodegroup-managed/vars.tf
compute/eks-ec2/dependencies.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf
compute/k8s-services/vars.tf
test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

This pull request introduces changes to the EKS node group management for scaling down EC2 instances after business hours. The changes replace the previous "inactivity cleanup" functionality with a new "scale to zero after business hours" feature. 
Key changes include:
**Variable and Local Updates:**
* Renamed `enable_inactivity_cleanup` to `enable_scale_to_zero_after_business_hours` across multiple files to better reflect the new functionality. [[1]](diffhunk://#diff-02c4dec2654cbdd6b9ee622b405117081a32a236919b3b6693162357784ce3daL110-R117) [[2]](diffhunk://#diff-73215c5737e0c7ae7f5fd46edf0f79c6108f8876a7b0b530c936d56a83230084L40-R50) [[3]](diffhunk://#diff-b18f8354ea8f3932f1be0681155c6e70c457a10798e9be3a07994adfea3d16b3L206-R221)
* Updated descriptions and comments to match the new …

Add enable_scale_to_zero_after_business_hours and use for scaling sandboxes down after business hours

---

_sub/compute/k8s-traefik-flux/values/helm-patch.yaml

This pull request includes a change to the `helm-patch.yaml` file to improve the match rule for the dashboard ingress route.
Improvements to match rule:
* [`_sub/compute/k8s-traefik-flux/values/helm-patch.yaml`](diffhunk://#diff-9554dc2f79ee28eca6234f05f5fbea1633c956a90f4e5eeb839681bb7c45eec8L26-R26): Updated the `matchRule` for the dashboard ingress route to use parentheses for better logical grouping.

Add missing parentheses around PathPrefix rules for the Traefik Dashboard ingressroute

---

compute/k8s-services/main.tf

This pull request includes a modification to the `compute/k8s-services/main.tf` file to enhance the configuration of the `traefik_alb_anon` module. The most important change involves updating the `subnet_ids` parameter to conditionally use different subnet IDs based on the `use_worker_nat_gateway` variable.
Changes in `compute/k8s-services/main.tf`:
* Updated the `subnet_ids` parameter to use `eks_control_subnet_ids` if `use_worker_nat_gateway` is true, otherwise use `eks_worker_subnet_ids`.
None. Reported by @samidbb on Slack.

Change subnets for traefik_alb_anon only when enabling NAT gateway

---

_sub/network/route-table/main.tf
_sub/network/route-table/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf

It turned out that having two pipelines managing the same route tables wasn't such a good idea after all....
This is a BREAKING change that requires some manual cleanup of Terraform state from the compute/eks-ec2 modules use of the _sub/network/route-table module.
This pull request introduces changes to support the conditional migration of VPC peering routes in the AWS infrastructure. The main enhancements include the addition of a new variable to control the migration and updates to the route table configurations to utilize this variable.
Key changes include:
* Added `migrate_vpc_peering_routes` variable to control the migration of VPC peering routes in `_sub/network/route-table/vars.tf` and `compute/eks-ec2/vars.tf`. This variable is a boolean with a default value of `false`. …

Add a feature toggle to determine if VPC Peering connections should automatically be migrated to new route tables. Default false

---

compute/k8s-services/main.tf

Reverts dfds/infrastructure-modules#1761 because it currentlys creates a 3 minutes outage when applying it.

Revert "Change subnets for traefik_alb_anon only when enabling NAT gateway"

---

_sub/compute/k8s-fluxcd/main.tf
_sub/compute/k8s-fluxcd/values/flux-system-patch.yaml
_sub/compute/k8s-fluxcd/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This pull request includes changes to add support for specifying an IAM role ARN for the source controller in the Flux CD configuration. The most important changes involve updating the Terraform configuration and adding a new variable to handle the IAM role ARN.
* [`_sub/compute/k8s-fluxcd/main.tf`](diffhunk://#diff-2e3be66af9677da6611ef57a5c721e764d0cda8b70ee86caa4ca9f9bb3c08b53L30-R32): Updated the `kustomization_override` to use `templatefile` and pass the `src_ctrl_arn` variable.
* [`_sub/compute/k8s-fluxcd/values/flux-system-patch.yaml`](diffhunk://#diff-3af6a8f87eefe902ab5a6ec8b1b5d23a3b12aa81af11090e712296eaa96d3ac6R31-R43): Added conditional logic to include a patch for the `ServiceAccount` if `src_ctrl_arn` is provided.
* …

Add support for IRSA for the Flux CD source controller

---

security/iam-ecr-access/main.tf
security/iam-ecr-access/providers.tf
security/iam-ecr-access/vars.tf
security/iam-ecr-access/versions.tf
security/iam-ecr-access/versions.tofu

- **Add directory structure for IAM resources in the shared-prod account**
- **Add module for seeting up IAM trust between Flux CD controller and IAM in an ECR account**
This pull request includes several changes to the `security/iam-ecr-access` module to support Flux CD source controller ECR access through IRSA, along with updates to providers, variables, and required versions. The most important changes include the addition of new IAM roles and policies, provider configurations, and variable definitions.
* Added IAM role and policy for Flux CD source controller ECR access, including trust relationships and policy attachments. (`security/iam-ecr-access/main.tf`)
* Added AWS provider configurations, including default tags and assume role settings for workload accounts. …

Add module for setting up IAM trust between Flux CD source controller and AWS account with ECR

---

_sub/security/hardened-account/main.tf
security/org-account-assume/main.tf

BREAKING CHANGE: Existing hardened accounts need to be using "terragrunt import" for 'module.hardened-account[0].aws_securityhub_account.workload[0]'
This pull request includes changes to improve the security and dependency management of the hardened account setup in AWS. The most important changes include the addition of a new resource for managing AWS Security Hub accounts and the introduction of dependencies to ensure proper resource creation order.
* [`_sub/security/hardened-account/main.tf`](diffhunk://#diff-b69fe7fdcb4985492eb3f79db2c2c0c869269ad6b0f9cbfedb343bd673b50ab7R9-R26): Added a new resource `aws_securityhub_account` to enable default security standards when the `harden` variable is true. This ensures that AWS Security Hub is properly configured for workload accounts.
* …

Make sure hardened accounts can be created from scratch by adding necessary dependencies

---

_sub/security/hardened-account/main.tf
_sub/security/hardened-account/vars.tf
security/org-account-assume/main.tf
security/org-account-assume/vars.tf

This pull request introduces changes to the Terraform configuration to allow for more flexibility in enabling default security standards. The most important changes include adding a new variable to control this behavior and updating the relevant modules to use this new variable.
* [`_sub/security/hardened-account/main.tf`](diffhunk://#diff-b69fe7fdcb4985492eb3f79db2c2c0c869269ad6b0f9cbfedb343bd673b50ab7L11-R11): Modified the `aws_securityhub_account` resource to use the new `enable_default_standards` variable instead of a hardcoded value.
* [`_sub/security/hardened-account/vars.tf`](diffhunk://#diff-6ca6c1f43bbe7a9826bf2dfcec00c67793abd315f46f05a5b233e02109d60ff8R64-R68): Added a new variable `enable_default_standards` with a default value of `false`.
* …

Disable default standards for security hub, and make it into a optional variable instead

---

_sub/security/iam-policies/main.tf

This pull request includes a small change to the IAM policy document in `main.tf`. The change adds a new permission, `sso:DescribeAccountAssignmentDeletionStatus`, to the `actions` list for the `aws_iam_policy_document` resource named `create_org_account`.

Add IAM action to watch recreation of SSO account assigments

---

_sub/compute/k8s-fluxcd/values/flux-system-patch.yaml

With the soon pretty big increase in helm releases due to ssu-k8s, to make sure helm controller is runner a bit smoother I want to bump the max concurrent ops.

Increase the amount of allowed concurrent ops for flux helm-controller

---

_sub/storage/velero/main.tf
_sub/storage/velero/values/patch.yaml
_sub/storage/velero/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This pull request introduces a new `read_only` variable to enable read-only access to Velero backup storage locations. This feature is designed to facilitate restoring backups without modifying the backup storage. The changes include updates to Terraform and Helm templates to support this functionality.
* [`_sub/storage/velero/vars.tf`](diffhunk://#diff-36860fab725b133094d511f993ea9f4ec62acf6f5eefd607f08d4cd1152a763dR161-R169): Added a new `read_only` variable with a default value of `false` and a description explaining its purpose.
* [`compute/k8s-services/vars.tf`](diffhunk://#diff-83380a112934c41699d826a5e1a07c6ee2d0729366db765c2d9c40fd2967c45bR906-R913): Added a corresponding `velero_read_only` variable for the Velero module.
* …

Add support for accessMode: ReadOnly in Velero in order to support restore from replicated bucket

---

security/org-policies/preventive.tf

This pull request includes a small update to the `security/org-policies/preventive.tf` file. The change adds a new IAM role, `OrgRole`, to the list of allowed roles in the preventive policy document.
* [`security/org-policies/preventive.tf`](diffhunk://#diff-2dd82fe79205b85e815f60da8ca94c104bd1b4536c0eae2afc329f8ca39d776aR210): Added `"arn:aws:iam::*:role/OrgRole"` to the `values` array for the `StringNotLike` condition in the `aws:PrincipalArn` variable.

Allow OrgRole to use s3:PutBucketPublicAccessBlock to deny public bucket ACL

---

_sub/storage/s3-bucket-lifecycle/main.tf
_sub/storage/s3-bucket-lifecycle/vars.tf
compute/k8s-services/vars.tf
storage/s3-velero-backup/vars.tf

This pull request refactors the handling of KMS encryption keys in S3 bucket replication configurations. The changes introduce separate variables and logic for source and destination KMS keys, improving clarity and flexibility in replication policies.
* `_sub/storage/s3-bucket-lifecycle/main.tf`: 
- Replaced `kms_encryption_key_arns` with `source_kms_key_arns` and `destination_kms_key_arns` for better distinction between source and destination KMS keys. Updated IAM policy documents and replication configurations to use these new variables. [[1]](diffhunk://#diff-b58282d7fd3f2d9fe8b950b6f94a8d638746989c7581a4951d4d583a4e6b0574L89-R95) [[2]](diffhunk://#diff-b58282d7fd3f2d9fe8b950b6f94a8d638746989c7581a4951d4d583a4e6b0574L134-R163) …

Support bucket encryption for bucket replication

---

compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Default behaviour: It will continue to work as it does now, unless you set a value for the variable "alb_az_app_registration_identifier_urls"
Why: Due to an API change in Azure, it'll no longer allow hostnames in identifier urls that isn't verified domains. That makes it more difficult when playing around with things in sandbox.

Allow for overriding the identifier urls set in the AZ app registration used for alb

---

.trunk/trunk.yaml
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

This pull request includes updates to version dependencies in configuration files, focusing on the Trunk CLI version and Helm chart versions for various services. These changes ensure the use of newer, more stable, or feature-rich versions.
* [`.trunk/trunk.yaml`](diffhunk://#diff-45a5a35dd7ad9a52d0fd3540f6c0d16a763575de51cc9a0a6c6f6a9f1da62ecdL5-R5): Updated the Trunk CLI version from `1.22.12` to `1.22.15` to incorporate the latest improvements or bug fixes.
* `test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl`:
- Updated the Helm chart version for the Traefik blue variant from `34.4.0` to `35.2.0`.
- Updated the Helm chart version for the Traefik green variant from `34.4.0` to `35.2.0`.
- Updated the Atlantis chart version from `5.7.0` to `5.17.2`.
- Updated the Velero Helm …

Upgrade helm charts for Traefik, Velero and Atlantis

---

_sub/network/vpc-peering-requester/main.tf
security/legacy-account-context/main.tf
security/org-account-context/main.tf

This pull request refactors the way IAM policies are attached to IAM roles by replacing the `managed_policy_arns` property with explicit `aws_iam_role_policy_attachment` resources. This change improves modularity and clarity in the Terraform configuration.
* [`_sub/network/vpc-peering-requester/main.tf`](diffhunk://#diff-102b9e9826581da57cda6e2b87f7c21b029eaac75b11e5e8414190104e07d554L277-R284): Replaced the `managed_policy_arns` property in the `aws_iam_role.ssm_tunnel` resource with a new `aws_iam_role_policy_attachment.ssm` resource to attach the `AmazonSSMManagedInstanceCore` policy.
* [`security/legacy-account-context/main.tf`](diffhunk://#diff-12809496af746334776e8375c9541251a01fed063a15dcc19490dc9633ebe209L143-R158): Removed the `managed_policy_arns` property from the …

Migrate deprecated managed_policy_arns to using aws_iam_role_policy_attachment

---

_sub/security/hardened-account/main.tf
_sub/security/hardened-account/vars.tf
security/legacy-account-context/main.tf
security/legacy-account-context/vars.tf
security/org-account-assume/main.tf
security/org-account-assume/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

BREAKING CHANGE:
These four variables are deprecated:
- hardened_security_contact_name
- hardened_security_contact_title
- hardened_security_contact_email
- hardened_security_contact_phone_number
Instead use:
- email_security
- primary_phone_number
These two are existing variables that are already used by the `alternate-contact` sub module.
This pull request refactors how AWS account alternate contact information is managed by removing redundant variables and resources from the `hardened-account` module and introducing a new reusable `alternate-contact` module. The changes aim to simplify the codebase and improve maintainability by centralizing the alternate contact logic.
* Removed the `aws_account_alternate_contact` resource and associated variables (`security_contact_name`, …

Use only one sub module for setting alternate security contact details

---

_sub/compute/atlantis/values/kubeconfigs.yaml
_sub/security/helm-1password-connect/dependencies.tf

BREAKING CHANGE: 
Requires External Secrets Operator to use external-secrets.io/v1 instead of external-secrets.io/v1beta1 in your Flux manifest repository too.
This pull request updates the `apiVersion` for resources using the `external-secrets.io` API to align with the latest version. The changes ensure compatibility with the updated API version.
* [`_sub/compute/atlantis/values/kubeconfigs.yaml`](diffhunk://#diff-fd803327123245972f08521bcacddc77607940902eedc0936c973ce22793852fL1-R1): Updated the `apiVersion` for the `ExternalSecret` resource from `v1beta1` to `v1`.
* [`_sub/security/helm-1password-connect/dependencies.tf`](diffhunk://#diff-09ae9456db86c758d054f434dbbe9976fc109be9626a3f52dac006dc9e984beeL76-R76): Updated the `apiVersion` for the `SecretStore` resource from `v1beta1` to …

Update apiVersion for External Secrets Operator

---

_sub/security/kms-key/main.tf
_sub/security/kms-key/outputs.tf
_sub/security/kms-key/vars.tf
_sub/security/kms-key/versions.tf
_sub/security/kms-key/versions.tofu
security/shared-symmetric-key/main.tf
security/shared-symmetric-key/outputs.tf
security/shared-symmetric-key/providers.tf
security/shared-symmetric-key/vars.tf
security/shared-symmetric-key/versions.tf
security/shared-symmetric-key/versions.tofu

This pull request introduces a reusable Terraform module for managing AWS KMS keys and integrates it into a `shared-symmetric-key` module for encrypting data at rest. Key changes include defining the KMS key module, configuring its variables, outputs, and dependencies, and setting up the `shared-symmetric-key` module to use it.
* [`_sub/security/kms-key/main.tf`](diffhunk://#diff-c89687942573f9349376ec5e4fe54b19d432577a8b85e584b8bfe87ca0c041f3R1-R80): Added a Terraform configuration to create a KMS key and alias, with a policy allowing administration and usage based on provided ARNs.
* [`_sub/security/kms-key/vars.tf`](diffhunk://#diff-a1943559a44971da74f95caaff3cfab2c6cc40d358cf826d3cb86ac0a9def5a7R1-R56): Defined variables for configuring the KMS key, including description, alias, …

Add modules for handling customer managed keys in KMS that can be used by multiple principals

---

_sub/security/kms-key/main.tf
_sub/security/kms-key/outputs.tf
_sub/security/kms-key/vars.tf
security/shared-symmetric-key/main.tf
security/shared-symmetric-key/outputs.tf
security/shared-symmetric-key/providers.tf
security/shared-symmetric-key/vars.tf

This pull request introduces support for multi-region AWS KMS keys, enabling the creation of replica keys in a secondary region. It also updates the module configurations and outputs to accommodate this feature. The most important changes are grouped below by theme.
* Added a new `multi_region` variable to control whether a KMS key should be multi-region. When enabled, a replica key is created in the secondary region (`_sub/security/kms-key/main.tf`, `_sub/security/kms-key/vars.tf`, [[1]](diffhunk://#diff-c89687942573f9349376ec5e4fe54b19d432577a8b85e584b8bfe87ca0c041f3R71-R97) [[2]](diffhunk://#diff-a1943559a44971da74f95caaff3cfab2c6cc40d358cf826d3cb86ac0a9def5a7R34-R39).
* Introduced a new `aws_kms_replica_key` resource to create the replica key, along with an alias for the replica …

Add multi-region support for shared KMS key

---

_sub/security/kms-key/main.tf

This pull request introduces a small but important update to the `aws_kms_replica_key` resource in the `_sub/security/kms-key/main.tf` file. The change ensures that the KMS replica key now uses a specific IAM policy document for its `policy` attribute.
* [`_sub/security/kms-key/main.tf`](diffhunk://#diff-c89687942573f9349376ec5e4fe54b19d432577a8b85e584b8bfe87ca0c041f3R89): Added the `policy` attribute to the `aws_kms_replica_key` resource, assigning it the JSON output of the `data.aws_iam_policy_document.this` data source.

Add missing policy to KMS replica keys

---

_sub/security/hardened-account/main.tf
_sub/security/hardened-account/vars.tf
security/legacy-account-context/main.tf
security/legacy-account-context/vars.tf
security/org-account-assume/main.tf
security/org-account-assume/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

This pull request introduces support for specifying default KMS keys for EBS encryption in multiple AWS account contexts. It adds new variables for primary and replica KMS key ARNs and updates the relevant modules to utilize these variables. Below is a breakdown of the most important changes:
* **New resources for default KMS keys**: Added `aws_ebs_default_kms_key` resources to enable default KMS key usage for EBS encryption in the hardened account module (`_sub/security/hardened-account/main.tf`). These resources are conditionally created based on the `harden` variable and the presence of KMS key ARNs.
* **Hardened account variables**: Introduced `kms_primary_key_arn` and `kms_replica_key_arn` variables in the hardened account module to allow specifying default KMS keys …

Add support for (optionally) specifying a KMS key as default encryption key for EBS volumns in hardened accounts.

---

_sub/security/kms-key/main.tf

This pull request updates the permissions in the IAM policy document for the KMS key to include additional grant-related actions. The changes ensure more comprehensive management capabilities for KMS grants.
IAM Policy Updates:
* [`_sub/security/kms-key/main.tf`](diffhunk://#diff-c89687942573f9349376ec5e4fe54b19d432577a8b85e584b8bfe87ca0c041f3L55-R57): Added `kms:ListGrants` and `kms:RevokeGrant` actions to the IAM policy document, alongside the existing `kms:CreateGrant` action, to enhance grant management capabilities.

allow additional permissions on EBS related kms for Terraform can handle resource lifecycle

---

_sub/compute/k8s-subnet-exporter/main.tf

This pull request updates the handling of IAM role policies in the `k8s-subnet-exporter` Terraform module to ensure compatibility with Terraform's JSON encoding/decoding requirements. The changes primarily involve wrapping policy documents with `jsonencode` and `jsondecode` for better parsing and validation.
* Updated `assume_role_policy` in `aws_iam_role` resource to use `jsonencode(jsondecode(...))` for the `subnet_exporter_trust` policy document.
* Updated `policy` in `aws_iam_role_policy` resource to use `jsonencode(jsondecode(...))` for the `subnet_exporter` policy document.

fix: encode IAM role assume policy and policy for subnet-exporter

---

_sub/storage/velero/main.tf
_sub/storage/velero/values/patch.yaml
_sub/storage/velero/vars.tf
azure-pipelines.yaml
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This pull request introduces support for integrating AWS KMS (Key Management Service) with Velero to enable encryption for EBS (Elastic Block Store) CSI volumes. The changes include updates to Terraform configurations, Helm chart values, and CI/CD pipeline variables to handle the new KMS functionality.
* Added a new IAM policy (`aws_iam_policy.kms_policy`) and role policy attachment (`aws_iam_role_policy_attachment.kms_policy_attach`) to grant Velero permissions for KMS operations like `Encrypt`, `Decrypt`, and `GenerateDataKey` based on the provided KMS ARN. These resources are conditionally created if the `ebs_csi_kms_arn` variable is set. (`_sub/storage/velero/main.tf`)
* Introduced a new Terraform variable `ebs_csi_kms_arn` to specify the ARN of the KMS key for EBS CSI encryption. …

Enable velero to restore volumes from shared EBS snapshots encrypted with KMS

---

compute/k8s-services/vars.tf

If you opt-out of using EBS encryption, it will currently fail with:
```
Error: Invalid template interpolation value
│
│   on ../../_sub/storage/velero/main.tf line 177, in resource "aws_iam_policy" "kms_policy":
│  150:   policy      = <<EOF
│  151: {
│  152:     "Version": "2012-10-17",
│  153:     "Statement": [
│  154:         {
│  155:             "Action": [
│  156:                 "kms:RevokeGrant",
│  157:                 "kms:ListGrants",
│  158:                 "kms:CreateGrant"
│  159:             ],
│  160:             "Condition": {
│  161:                 "Bool": {
│  162:                     "kms:GrantIsForAWSResource": "true"
│  163:                 }
│  164:             },
│  165:             "Effect": "Allow",
│  166:             "Resource": "${var.ebs_csi_kms_arn}"
│ …
```

fix: update default values for velero_ebs_csi_kms_arn variables. Use empty string instead of null

---

_sub/compute/eks-cluster/network.tf
_sub/compute/eks-cluster/vars.tf
_sub/network/vpc-peering-requester/main.tf
_sub/network/vpc-peering-requester/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf
test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

- The complex variables `vpc_peering_settings_eu_west_1` and `vpc_peering_settings_eu_central_1` previously had a mandatory field called `cidr_block_peer`. This has been renamed to `peer_cidr_block` to following the naming standard with other fields in this variable.
- This is only a breaking changes for pipelines that use the `org-account-context` module AND has VPC peering enabled. The migration path is to run Search/Replace in all the terragrunt.hcl files that has `vpc_peering_settings_eu_west_1` and `vpc_peering_settings_eu_central_1`  and replace `cidr_block_peer` with  `peer_cidr_block`.
This pull request introduces several changes across multiple Terraform modules and files. The main focus is on enhancing configurability by introducing new variables and renaming existing ones for …

Data lookups as primary way to find route tables for peering

---

_sub/storage/velero/values/patch.yaml

This pull request includes a change to the `volumeSnapshotLocation` configuration in the `patch.yaml` file for Velero storage settings. The change renames the key and adds a `name` field to improve clarity and configuration specificity.
Velero storage configuration changes:
* [`_sub/storage/velero/values/patch.yaml`](diffhunk://#diff-9bcea7b85ef86a4cd2047a80b14dede9dbbe7721053b6efd7ef3a1745aeaebd9L38-R40): Renamed `VolumeSnapshotLocation` to `volumeSnapshotLocation` and added a `name` field (`velero-snapshot`) to the configuration.

fix(velero): correct casing for volumeSnapshotLocation and add name field

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl

This pull request includes a small change to the `terragrunt.hcl` file in the `k8s-qa` service configuration. The change disables the deployment of the `kube-prometheus-stack` by setting `monitoring_kube_prometheus_stack_deploy` to `false`.

fix(terragrunt): disable kube-prometheus-stack deployment in configuration

---

_sub/compute/eks-nodegroup-managed/dependencies.tf

This PR fixes the default AMI filter for nodes to use AL2023 as expected

fix: use ami al2023 filter

---

_sub/security/org-account-query/main.tf
_sub/security/org-account-query/outputs.tf
network/ipam/main.tf
network/ipam/vars.tf

This pull request introduces changes to enhance flexibility and functionality in querying AWS Organizational Units (OUs) and sharing IPAM pools. The most significant updates include adding new data sources for querying OUs, updating logic for determining principals in resource sharing, and introducing new variables to support more granular control over IPAM pool sharing.
* Added new data sources in `_sub/security/org-account-query/main.tf` to retrieve the AWS organization and its descendant OUs for more comprehensive querying.
* Updated `outputs.tf` to include an output for the list of descendant organizational units, enabling downstream modules to access this data.
* Modified `network/ipam/main.tf` to dynamically compute principals for sharing IPAM pools based on either specific OU names …

Allow IPAM pool sharing with OUs instead of per account basis

---

test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl

Pins EBS CSI Driver version in QA and adds renovate filter for it

fix: pin ebs csi driver in qa and manage with renovate

---

network/ipam/main.tf
network/ipam/vars.tf

- The `network/ipam` module has breaking changes, which means that `terraform/terragrunt/tofu import` should be run prior to `apply` in order to migrate the ipam configuration to the new standard.
This pull request refactors the IPAM pool Terraform configuration to make it more generic, scalable, and easier to manage. The changes consolidate repeated module definitions into dynamic, data-driven constructs, and move sharing configuration into the main `ipam_pools` variable for improved flexibility. The most important changes are grouped below:
* Replaced multiple hardcoded pool modules (`platform_pool`, `capabilities_pool`, `reserve_pool`) with a single dynamic `sub_pools` module using `for_each` over `ipam_pools`, allowing any number of pools except "main" to be defined in the input …

fix: update resource association for_each to use index mapping

---

test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
test/integration/hooks/custom_hook_01.sh

This pull request introduces updates to the deployment process for External Secrets Operator (ESO) and improves the custom integration hook script. The main changes focus on specifying the ESO Helm chart version and ensuring the correct Custom Resource Definitions (CRDs) are applied or upgraded during integration tests.
**External Secrets Operator deployment improvements:**
* Added the `external_secrets_helm_chart_version` input to the `terragrunt.hcl` configuration to specify the ESO Helm chart version.
* Updated the custom hook script to check if ESO is installed and, if so, automatically apply or upgrade the ESO CRDs using the version defined in `terragrunt.hcl`.
**Script clarity and robustness:**
* Clarified the namespace check in `custom_hook_01.sh` to specifically reference the …

feat(external-secrets): add helm chart version input and update custom hook for ESO installation

---

.github/workflows/qa.yml

This pull request introduces a new GitHub Actions workflow for automated QA testing and provisioning in the repository. The workflow builds and tests binaries for both the master and feature branches, provisions infrastructure using secrets from 1Password, and runs integration tests on provisioned environments.
* Added a new workflow file `.github/workflows/qa.yml` that automates building, provisioning, and testing for both master and feature branches using GitHub Actions.
* Configured jobs to build test binaries for master and feature branches in isolated containers, leveraging Go build cache for faster builds.
* Uploaded built test binaries as artifacts for use in downstream jobs.
* Added jobs to provision infrastructure (EKS clusters, S3 buckets, Velero) using custom scripts …

Add QA pipeline workflow for testing and provisioning

---

_sub/security/iam-github-oidc-provider/main.tf

BREAKING CHANGE:
Users of GitHub OIDC integration needs to update their branch filers since 'ref:' is no longer added to the string. This is to ensure better compability with wildcard branch patterns.
This pull request makes a small adjustment to the trust policy document for the GitHub OIDC provider in the IAM configuration. The change updates the format of the values used in the `StringLike` condition to ensure correct matching of repository references.
* Changed the format string in the `values` field from `"repo:%s:ref:%s"` to `"repo:%s:%s"` in the `aws_iam_policy_document` data block, simplifying how repository references are specified for OIDC authentication.

fix: correct format in OIDC role assumption condition

---

_sub/security/iam-github-oidc-provider/vars.tf
security/oidc-github-workflows/vars.tf
security/org-account/vars.tf

This pull request removes the validation blocks from several Terraform variable definitions that previously enforced git ref formatting for repositories used in GitHub OIDC authentication. The main impact is that Terraform will no longer check that refs start with `refs/heads/` or `refs/tags/` for these variables, potentially allowing more flexible (but less strictly validated) input.
Validation removal for repository ref inputs:
* [`_sub/security/iam-github-oidc-provider/vars.tf`](diffhunk://#diff-74a62e9af9cb0c765f31f5ca7b42297b4dfdcb781e213d87084857ab28f4e571L7-L10): Removed the validation block from the `repositories` variable, so refs are no longer checked to start with `refs/heads/` or `refs/tags/`.
* [`security/oidc-github-workflows/vars.tf`](diffhunk://#diff-af1f9eb267b38882717adce …

refactor: remove validation for repository refs in OIDC variables

---

_sub/compute/lambda/lambda-from-archive/versions.tf
_sub/compute/lambda/lambda-from-archive/versions.tofu

This pull request updates the Terraform provider configuration for the Lambda from Archive module, specifically changing the archive provider source to use the correct name. This ensures compatibility and proper provider usage in both Terraform and OpenTofu configurations.
Provider configuration updates:
* Changed the archive provider source from `hashicorp/archive-file` to `hashicorp/archive` in `_sub/compute/lambda/lambda-from-archive/versions.tf` to use the correct provider name.
* Made the same provider source change in `_sub/compute/lambda/lambda-from-archive/versions.tofu` for consistency with OpenTofu.

fix: correct provider source for archive in versions.tf and versions.tofu

---

compute/k8s-services/main.tf
compute/k8s-services/vars.tf

Helm chart version variable introduced but never exposed blocking version locking.

Exposed 1password-connect helm chart version as variable to enable locking

---

_sub/security/azure-app-registration/dependencies.tf
_sub/security/azure-app-registration/main.tf
_sub/security/azure-app-registration/vars.tf
compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This pull request introduces support for specifying additional Azure AD application owners through a new variable, improving flexibility and maintainability for application registration ownership. The changes allow passing a list of owner object IDs in addition to the default owner, and propagate this option throughout the relevant modules and variables.
This enables managing AD app registration in sandbox environment to be able to for example to get notification on certificates expiration and renewal.
**Azure AD Application Ownership Enhancements:**
* Added a new variable `additional_owner_ids` in `_sub/security/azure-app-registration/vars.tf` to allow specifying extra owner object IDs for Azure AD applications.
* Updated the `locals` block in …

enable adding custom owners on azure AD besides from default owner

---

security/org-policies/preventive.tf

This pull request introduces a security enhancement to the organization-wide preventive IAM policy by adding a condition to restrict certain GuardDuty actions. The change ensures that only roles matching a specific naming pattern are allowed to perform sensitive operations.
Security policy improvements:
* Added a `StringNotLike` condition to the `aws:PrincipalArn` variable in the `preventive` IAM policy document, restricting the listed GuardDuty actions to principals with ARNs matching `arn:aws:iam::*:role/OrgRole`.

feat(security): add condition to deny actions for specific IAM role

---

_sub/security/ssm-parameter-store/main.tf
_sub/security/ssm-parameter-store/vars.tf
compute/eks-ec2/main.tf
compute/eks-ec2/vars.tf
security/org-account-context/dependencies.tf
security/org-account-context/main.tf
security/org-account-context/vars.tf

BREAKING CHANGE:
- This release is backward compatible with existing logic.
- Our account pipeline need a new variable set before this release can be used: 
```
variable "oidc_provider" {
type = map(object({
cluster_oidc_url = string
cluster_name     = string
}))
description = "IAM OIDC Providers for the capability account to trust EKS clusters service accounts"
}
```
This pull request refactors how OIDC providers are managed in the organization account context, transitioning from single OIDC provider variables to a map-based structure that supports multiple providers. The changes improve scalability and flexibility for environments with multiple EKS clusters. Additionally, the PR introduces a new IAM role for standby accounts and updates SSM parameter modules for backward compatibility …

feat: refactor OIDC provider configuration for multiple clusters and add standby IAM role

---

compute/k8s-services/main.tf
compute/k8s-services/vars.tf

This pull request introduces a minor improvement to the configuration of Atlantis GitHub repositories and removes an unused variable from the External DNS settings. These changes help ensure consistent behavior and clean up unused code.
Configuration improvements:
* Sorted the `github_repositories` input for the `atlantis_github_configuration` module to ensure a consistent order when passing repository names.
Code cleanup:
* Removed the unused `external_dns_domain_filterss` variable from `vars.tf`, reducing clutter and potential confusion in the configuration.

fix: sort github repositories for atlantis configuration

---

_sub/compute/druid-operator/values/kustomization.yaml
_sub/compute/github-arc-runners/dependencies.tf
_sub/compute/github-arc-ss-controller/dependencies.tf
_sub/compute/k8s-traefik-flux/main.tf
_sub/compute/k8s-traefik-flux/values/helm-install.yaml
_sub/compute/keda/values/kustomization.yaml
_sub/compute/nvidia-device-plugin/values/kustomization.yaml
_sub/compute/trivy-operator/values/kustomization.yaml
_sub/monitoring/blackbox-exporter/values/kustomization.yaml
_sub/monitoring/goldpinger/main.tf
_sub/monitoring/goldpinger/values/kustomization.yaml
_sub/monitoring/grafana/values/kustomization.yaml
_sub/monitoring/metrics-server/dependencies.tf
_sub/network/external-dns/values/helm-install.yaml
_sub/security/external-secrets/dependencies.tf
_sub/security/falco/values/kustomization.yaml
_sub/storage/velero/values/kustomization.yaml

This pull request updates the way Kustomize patches are applied across multiple Kubernetes-related modules, standardizing the patch format and improving HelmRelease targeting. Additionally, it introduces more granular patch definitions for some resources and adds variable support for specific values. These changes help ensure more reliable and maintainable deployments.
**Kustomize patching improvements:**
* Replaces the deprecated `patchesStrategicMerge` directive with the newer `patches` format in all relevant `kustomization.yaml` and Terraform files, allowing for more precise targeting of `HelmRelease` resources by kind, name, and namespace. [[1]](diffhunk://#diff-6f828eec98cf12049703e649bd418bb8e1c531c8dd720146172a433a355a83ffL5-R10) …

refactor: update kustomization patches to use new format for HelmRelease targets

---

_sub/security/helm-1password-connect/dependencies.tf
_sub/security/helm-1password-connect/iam.tf
_sub/security/helm-1password-connect/main.tf
_sub/security/helm-1password-connect/vars.tf
compute/k8s-services/main.tf

This is a minor change, because deploy_name and namespace was _hardcoded_ in the service module.
This pull request refactors the Helm deployment module for 1Password Connect by standardizing the deployment name and namespace handling, simplifying variable usage, and streamlining file generation and patching. The changes improve maintainability and reduce the number of required input variables, making the module easier to use and less error-prone.
**Refactoring and Standardization**
* The deployment name is now set as a local variable (`local.deploy_name`), removing the need for the `deploy_name` input variable and ensuring consistency across all references. (`_sub/security/helm-1password-connect/dependencies.tf`, [[1]](diffhunk://#diff-09ae9456db86c758d054f434dbbe9976fc109be9626a3f52dac006 …

refactor: standardize deployment name usage and remove redundant variables in 1Password Connect configuration. Also use post build substitution
